### ISSUE TITLE
HC: extract / generate HSA device code only?

### ISSUE THREAD

**Issue by j-stephan** [RadeonOpenCompute/hcc#1002]
I'd like to view the device code that is generated for HC kernels. How can I achieve this? `hcc` doesn't have any obvious options, and using the `extractkernel` script fails with the following message:

`Incorrect magic string at /opt/rocm/bin/extractkernel line 58.`

My GPU target is gfx900, I'm using the latest ROCm version from the Ubuntu 16.04 repository.

**Comment by aaronenyeshi** [comment]
Before building your application, you can use `export KMDUMPLLVM=1` to dump the llvm IR. And use `export KMDUMPISA=1` to dump the ISA. Using `export KMDUMPDIR=\path\to\dir` to select the dump location otherwise it will dump in current dir.
For extractkernel, did you run it on the executable that was generated by HCC?

**Comment by j-stephan** [comment]
Thanks, those exports seem to work.

> For extractkernel, did you run it on the executable that was generated by HCC?

Yes:

```
$ hcc `hcc-config --cxxflags --ldflags` -O3 -std=c++17 nbody.cpp -o nbody -Wall -Wextra -pedantic -amdgpu-target=gfx900
$ ls
nbody  nbody.cpp
$ extractkernel -i nbody
Incorrect magic string at /opt/rocm/bin/extractkernel line 58.
```

**Comment by aaronenyeshi** [comment]
Thanks for kzhuravl: https://github.com/RadeonOpenCompute/hcc/pull/1004

**Comment by j-stephan** [comment]
I can confirm that #1004 fixes the issue with the script. Since there are now two ways of extracting the ISA this issue can be closed IMHO.

**Comment by ghostplant** [comment]
@aaronenyeshi How can I use `llc` to compile the ll code (dumped via KMDUMPLLVM) to amdgpu HSACO target module?

**Comment by aaronenyeshi** [comment]
If it's .ll code, it needs to be first transformed into .bc (bitcode) form. You can do that using `llvm-as`. then to lower into HSA ISABIN, use `llc -mtriple amdgcn-amd-amdhsa -mcpu=gfx900 -mattr=-code-object-v3 -O2 -amdgpu-function-calls=0 -filetype=obj -o <output1>.isabin <input>.bc`. Then to transform into .hsaco use `ld.lld -shared <output1>.isabin -o <output2>.hsaco`.

**Comment by ghostplant** [comment]
@aaronenyeshi Thank you, but I still got some errors:

This is the single-file LLVM code for amdgpu generated by TVM:
```c
; ModuleID = 'matmul_kernel0'
source_filename = "matmul_kernel0"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-ni:7"
target triple = "amdgcn-amd-amdhsa-hcc"

@.shared = private unnamed_addr addrspace(3) global [2 x float]
@.shared.1 = private unnamed_addr addrspace(3) global [2 x float]

; Function Attrs: nounwind
define dllexport amdgpu_kernel void @matmul_kernel0(float addrspace(1)* noalias nocapture readonly, float addrspace(1)* noalias nocapture readonly, float addrspace(1)* noalias nocapture) local_unnamed_addr #0 {
entry:
  %3 = alloca [2 x float], align 4, addrspace(5)
  %4 = alloca [2 x float], align 4, addrspace(5)
  %5 = tail call i32 @llvm.amdgcn.workgroup.id.y()
  %6 = icmp slt i32 %5, 64
  br i1 %6, label %if_then1, label %if_end7.3, !prof !4
  ..
  ..
```

I want to compile it into an HSACO file so that I can load it by hipModuleLoad and do something more after that.

I follow your instructions, but failed to transform it into bc form (using latest LLVM-9):
```sh
/root$ llvm-as-9 llvm_code.ll
llvm-as-9: llvm_code.ll:7:1: error: global variable reference must have pointer type
@.shared.1 = private unnamed_addr addrspace(3) global [2 x float]
^
```
Seems like llvm-as doesn't understand this shared memory variable?

**Comment by ghostplant** [comment]
@aaronenyeshi The problem is solved, just because global value of private type should be external type.
