### ISSUE TITLE
half float usage

### ISSUE THREAD

**Issue by PhilipDeegan** [RadeonOpenCompute/hcc#1045]
Hey there folks,

Do you have a suggested method for using halfs with ROCm?

I don't know of a standard half, so please let me know how it might be used.

**Comment by AlexVlx** [comment]
`_Float16` (http://clang.llvm.org/docs/LanguageExtensions.html#half-precision-floating-point) is the preferred alternative (note that due to recent changes in Clang there may be a temporary hiccup around this).

**Comment by PhilipDeegan** [comment]
much obliged @AlexVlx
