### ISSUE TITLE
Illegal instruction error with HCC version, 1.3.19045-fea3e2b-683c680-6e349ce

### ISSUE THREAD

**Issue by mythreyi22** [RadeonOpenCompute/hcc#1055]
Hello,
HcSparse calls are crashing with Illegal instruction error with HCC version, 1.3.19045-fea3e2b-683c680-6e349ce[ rocm 2.1]. With the previous HCC  versions, the HcSparse calls and HcSparse unit tests run successfully. 

The problem can be experienced with  HcSparse unit tests.
HcSparse tests : 
./nnz_float_test_API 
Successfully initialized sparse library
successfully created mat descriptor
Illegal instruction (core dumped)

Any pointers to the source of the problem?

Thanks,
Mythreyi P

**Comment by david-salinas** [comment]
Please take a look, and try out, rocSPARSE https://github.com/ROCmSoftwarePlatform/rocSPARSE , HcSparse is not currently being maintained.

**Comment by mythreyi22** [comment]
It was an issue wrt my local HCC, Hcsparse works fine. Thank you.
