### ISSUE TITLE
HCC no longer builds

### ISSUE THREAD

**Issue by pfultz2** [RadeonOpenCompute/hcc#1078]
Building the latest hcc from clang_tot_upgrade, I get this error:

```
CMake Error at CMakeLists.txt:115 (MESSAGE):
  ROCm Device Libs not found.  Use
  -DROCM_DEVICE_LIB_DIR=<path_to_ocml.amdgcn.bc>.
```

This seems to be related to PR #1017, which suggest I use the installed rocm-device-libs package. However, after installing the rocm-device-libs package, I get this error:

```
hcc/build/compiler/bin/llvm-link: /opt/rocm/lib/hip.amdgcn.bc: error: Could not open input file: No such file or directory
hcc/build/compiler/bin/llvm-link: error:  loading file '/opt/rocm/lib/hip.amdgcn.bc'
hcc/build/compiler/bin/llvm-link: /opt/rocm/lib/hip.amdgcn.bc: error: Could not open input file: No such file or directory
Generating AMD GCN kernel failed in llvm-link with ROCm-Device-Libs for target: gfx906
hcc/build/compiler/bin/llvm-link: error:  loading file '/opt/rocm/lib/hip.amdgcn.bc'
hcc/build/compiler/bin/llvm-link: /opt/rocm/lib/hip.amdgcn.bc: error: Could not open input file: No such file or directory
hcc/build/compiler/bin/llvm-link: error:  loading file '/opt/rocm/lib/hip.amdgcn.bc'
Generating AMD GCN kernel failed in llvm-link with ROCm-Device-Libs for target: gfx900
Generating AMD GCN kernel failed in llvm-link with ROCm-Device-Libs for target: gfx803
clang-8: error: linker command failed with exit code 7 (use -v to see invocation)
cmake-tests/CMakeFiles/cmake-test.dir/build.make:97: recipe for target 'bin/cmake-test' failed
make[2]: *** [bin/cmake-test] Error 7
CMakeFiles/Makefile2:139244: recipe for target 'cmake-tests/CMakeFiles/cmake-test.dir/all' failed
make[1]: *** [cmake-tests/CMakeFiles/cmake-test.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

So it seems I need to build a newer rocm-device-libs package, but I need the hcc compiler to do that, which is what I am currently compiling creating a circular dependency. 

I think PR#1017 should reverted. It seems like the compiler is strongly dependent on the rocm device lib version and should therefore be built as part of building the compiler.

**Comment by david-salinas** [comment]
Hi Paul.   I'm looking at this, to see if I can reproduce.  So far our existing HCC build/test jobs have been fine using the Device-Lib installed; though we're using a docker container that always grabs the latest available from the Debian server.

After updating Device-Libs, you may need to clear out your build directory (I don't trust make clean, I just "rm -rf build/").  If you can verify that "/opt/rocm/lib/hip.amdgcn.bc" exists on your system, you shouldn't be getting those llvm-lnk errors.

**Comment by pfultz2** [comment]
This is after doing `rm -rf build` on the directory. This is using the rocm-device-libs from rocm 1.9.2.

**Comment by david-salinas** [comment]
So I can't reproduce this error.

HCC's CMakeLsits.txt file tries to find the Device Library with this code: https://github.com/RadeonOpenCompute/hcc/blob/a40a877bb78d7af766e3d7ea6eb2d8157c3818bc/CMakeLists.txt#L105 

Can you see if the device libs are in /opt/rocm/lib?  Look for ocml.amdgcn.bc.  If they're not there, you may need to reinstall the Device Libs into the default location.  Or if you're using a non-default location (not /opt/rocm/), add the location path when you call cmake with "-DROCM_DEVICE_LIB_DIR=<path to ocml.amdgcn.bc>"

**Comment by scchan** [comment]
@pfultz2  could you try with a newer device library package from rocm 2.1 or 2.2?

**Comment by pfultz2** [comment]
> Can you see if the device libs are in /opt/rocm/lib?

Yes:

```
~ $ ll /opt/rocm/lib
total 84668
drwxrwxr-x  3 root root     4096 Mar  7 10:38 ./
drwxrwxr-x 15 root root     4096 Mar  7 10:37 ../
drwxr-xr-x  2 root root     4096 Mar  7 10:38 cmake/
-rw-r--r--  1 root root    57804 Nov 13 14:30 hc.amdgcn.bc
lrwxrwxrwx  1 root root       26 Mar  7 10:38 .hipInfo -> /opt/rocm/hip/lib/.hipInfo
-rw-r--r--  1 root root    17020 Nov 13 14:30 irif.amdgcn.bc
lrwxrwxrwx  1 root root       47 Mar  7 10:38 libclang_rt.builtins-x86_64.a -> /opt/rocm/hcc/lib/libclang_rt.builtins-x86_64.a
-rw-r--r--  1 root root 80854392 Nov 13 15:06 libcomgr.so
lrwxrwxrwx  1 root root       64 Jun 14  2018 libCXLActivityLogger.so -> ../profiler/CXLActivityLogger/bin/x86_64/libCXLActivityLogger.so*
lrwxrwxrwx  1 root root       29 Mar  7 10:38 libhc_am.so -> /opt/rocm/hcc/lib/libhc_am.so
lrwxrwxrwx  1 root root       31 Nov 13  2017 libhcfft.so -> /opt/rocm/hcfft/lib/libhcfft.so
lrwxrwxrwx  1 root root       33 Mar  7 10:38 libhip_device.a -> /opt/rocm/hip/lib/libhip_device.a
lrwxrwxrwx  1 root root       32 Nov 13  2017 libhipfft.so -> /opt/rocm/hcfft/lib/libhipfft.so
lrwxrwxrwx  1 root root       31 Mar  7 10:38 libhip_hcc.so -> /opt/rocm/hip/lib/libhip_hcc.so
lrwxrwxrwx  1 root root       37 Mar  7 10:38 libhip_hcc_static.a -> /opt/rocm/hip/lib/libhip_hcc_static.a
lrwxrwxrwx  1 root root       14 Nov 13 14:16 libhsakmt.so -> libhsakmt.so.1
lrwxrwxrwx  1 root root       18 Nov 13 14:16 libhsakmt.so.1 -> libhsakmt.so.1.0.9
-rw-r--r--  1 root root   136800 Nov 13 14:16 libhsakmt.so.1.0.9
lrwxrwxrwx  1 root root       32 Nov 13 14:17 libhsa-runtime64.so -> ../hsa/lib/libhsa-runtime64.so.1
lrwxrwxrwx  1 root root       36 Mar  7 10:38 libmcwamp_atomic.a -> /opt/rocm/hcc/lib/libmcwamp_atomic.a
lrwxrwxrwx  1 root root       34 Mar  7 10:38 libmcwamp_cpu.so -> /opt/rocm/hcc/lib/libmcwamp_cpu.so
lrwxrwxrwx  1 root root       34 Mar  7 10:38 libmcwamp_hsa.so -> /opt/rocm/hcc/lib/libmcwamp_hsa.so
lrwxrwxrwx  1 root root       30 Mar  7 10:38 libmcwamp.so -> /opt/rocm/hcc/lib/libmcwamp.so
-rw-r--r--  1 root root  2681856 Nov 13 15:05 librocr_debug_agent64.so
-rw-r--r--  1 root root   133032 Nov 13 14:30 ockl.amdgcn.bc
-rw-r--r--  1 root root     2320 Nov 13 14:30 oclc_correctly_rounded_sqrt_off.amdgcn.bc
-rw-r--r--  1 root root     2320 Nov 13 14:30 oclc_correctly_rounded_sqrt_on.amdgcn.bc
-rw-r--r--  1 root root     2300 Nov 13 14:30 oclc_daz_opt_off.amdgcn.bc
-rw-r--r--  1 root root     2300 Nov 13 14:30 oclc_daz_opt_on.amdgcn.bc
-rw-r--r--  1 root root     2308 Nov 13 14:30 oclc_finite_only_off.amdgcn.bc
-rw-r--r--  1 root root     2308 Nov 13 14:30 oclc_finite_only_on.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_700.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_701.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_702.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_801.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_802.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_803.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_810.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_900.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_902.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_904.amdgcn.bc
-rw-r--r--  1 root root     2316 Nov 13 14:30 oclc_isa_version_906.amdgcn.bc
-rw-r--r--  1 root root     2308 Nov 13 14:30 oclc_unsafe_math_off.amdgcn.bc
-rw-r--r--  1 root root     2308 Nov 13 14:30 oclc_unsafe_math_on.amdgcn.bc
-rw-r--r--  1 root root   197340 Nov 13 14:30 ocml.amdgcn.bc
-rw-r--r--  1 root root  2506688 Nov 13 14:30 opencl.amdgcn.bc
```

**Comment by scchan** [comment]
The files' date (Nov 13) seems to indicate that you have an older version.  I installed the one from rocm 2.2 (Mar 7) and that package includes hip.amdgcn.bc, which is missing in your directory.

**Comment by pfultz2** [comment]
So where is the cmake build scripts to build a newer rocdl with hcc?

**Comment by david-salinas** [comment]
I would suggest removing the existing rocm-device-libs package with: "sudo apt-get --purge remove rocm-device-libs".  Then, make sure you're using the radeon debian repo with these commands:

wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | sudo apt-key add -
echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main' | sudo tee /etc/apt/sources.list.d/rocm.list

then install (latest) Device Libs with:

   sudo apt-get install rocm-device-libs

Unless you're making changes to the device library, I don't think you need to build/install it.  Just grab the latest from the Debian repository.

But you could also consider using docker containers to do your work in.  I didn't really like them too much myself in the beginning.  But I've found them incredibly useful for installing/building ROCm components, and keeping my development machines "clean".  They're like mini-VMs.

**Comment by scchan** [comment]
There isn't a new build script for rocdl to build with hcc.  The normal build process is to build clang and llvm first.

If you are up to the point in the hcc build where the LLD complains about missing a builtin file, then you could point the rocdl build to the clang compiler from hcc through the `CC=` variable and also specify the `LLVM_DIR` to point to the `compiler` directory in `hcc`.  I haven't tried it but some slight tweak to that may make it work.

https://github.com/RadeonOpenCompute/ROCm-Device-Libs#building

**Comment by pfultz2** [comment]
>I would suggest removing the existing rocm-device-libs package with: "sudo apt-get --purge remove rocm-device-libs". Then, make sure you're using the radeon debian repo with these commands:

We are pulling from the 1.9.2 archive repos from [here](http://repo.radeon.com/rocm/archive/). This is to match what we have on the host.

**Comment by pfultz2** [comment]
> The normal build process is to build clang and llvm first.

Where is the repo for those? The readme suggests pulling from the "amd-common" branch across several repos, which is what we do *NOT* want to do since it is not reproducible. Is there a repo we can clone that has the submodules for clang and llvm with a cmake build script to build?

**Comment by scchan** [comment]
It works with clang and llvm trunk.  You can also try fetching hcc's clang and llvm, run hcc's cmake, build only clang/llvm/llvm with `make clang; make lld` and then use those binaries to build rocdl

**Comment by david-salinas** [comment]
Hi @pfultz2 , so we recently did reverse PR #1017 with PR #1083 .  With newest HCC (in clang_tot_upgrade branch) this issue should be resolved.  Can you confirm ?  Thanks.
