### ISSUE TITLE
return kernel execution error instead of program crash

### ISSUE THREAD

**Issue by ghostplant** [RadeonOpenCompute/hcc#1150]
Is it possible to avoid such abort message which fully terminates the user applications? In the context of HIP, can it be replaced by an error return value when doing `hipStreamSynchronization()`?
```sh
Memory access fault by GPU node-1 (Agent handle: 0x1e10ee0) on address 0x7fb884801000. Reason: Page not present or supervisor privilege.
```

**Comment by scchan** [comment]
Currently I believe only the Debug Agent could intercept this. 
I'm going to close this since further discussion should happen in HIP

**Comment by ghostplant** [comment]
@scchan Thanks, it is important for the GPU kernel not to crash unexpectedly. Such errors include not only `page access`, but also `invalid GPU kernel` error.
