### ISSUE TITLE
Where is the definition of `__ockl_sdot2`

### ISSUE THREAD

**Issue by ghostplant** [RadeonOpenCompute/hcc#1188]
`__ockl_sdot2` is used by `amd_mixed_dot`, and I want to see how the `saturate` influences the result. By tracing all the source codes from hcc and HIP, I didn't see such implementation of `__ockl_sdot2` anywhere, so I won't know how `saturate` works. Can anyone provide more information about `saturate` argument from `__ockl_sdot2`?

**Comment by b-sumner** [comment]
It works just like the clamp bit works on other instructions.  Anyway, see https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/ockl/src/dots.cl#L56

**Comment by b-sumner** [comment]
Ugh.  I see a bug in the software implementation though.  Should be fixed soon.

**Comment by ghostplant** [comment]
@b-sumner Thanks, if I use gfx906 which supports hardward dot4 for int8, will `saturate=true` be slower than `saturate=false` since it requires extra boundary checking?

**Comment by ghostplant** [comment]
@b-sumner Besides, as I am recently using this device call, can you tell me what bug it is?

**Comment by b-sumner** [comment]
The software implementation was using an int where a long was required on line 62.

**Comment by ghostplant** [comment]
@b-sumner Thanks! It doesn't matter as I am only using gfx906 instead of older arches.
