### ISSUE TITLE
LLVM-MC does not support `ds_add_f32`

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/hcc#122]
I wasn't sure where to put this issue, since the `llvm` repository does not allow posting issues. The `llvm-mc` currently does not implement a number of instructions. In particular, I need `ds_add_f32`

**Comment by atamazov** [comment]
Thanks for reporting the ds_add_f32 issue. We are preparing the fix.
BTW you can register at llvm bugzilla and report issues there.

**Comment by atamazov** [comment]
Patch it in review https://reviews.llvm.org/D24765

**Comment by atamazov** [comment]
Fix committed r282086

**Comment by almson** [comment]
Thanks!
