### ISSUE TITLE
How to compile to HSACO

### ISSUE THREAD

**Issue by almson** [RadeonOpenCompute/hcc#123]
How can I compile an HCC kernel into an HSACO binary that can be loaded in HSA?

**Comment by adityaatluri** [comment]
Hi,
Currently, there is no command line option to dump code object from HCC.
The work around is setting env variables KMDUMPISA or KMDUMPLLVM[1] to 1. Which dumps ISA and LLVM IR respectively. Once you get the ISA, you can use clang(4.0) or llvm-mc and clang shipped with ROCm to generate code object. I wrote a sample which generates code object from LLVM IR and ISA [2]. Hope it'll be useful.

This is not recommended as it is not the intended way of generating ISA. 

The new developer-preview branch on HIP can now generates code object from kernel using hipcc. You can checkout vector copy sample here [3]. Although the sample is HIP kernel, you can try writing kernel in HCC.

[1]. https://github.com/RadeonOpenCompute/hcc/blob/master/lib/clamp-hsatools.in
[2]. https://gist.github.com/adityaatluri/d8ed1f66024840f8cb982ef585b7c31f
[3]. https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/tree/developer-preview/samples/0_Intro/module_api

**Comment by almson** [comment]
Thanks! That was very helpful. I'll try the HIP method.

**Comment by bensander** [comment]
HIP is probably best supported flow for this right now but we are also providing some tools so you can do this a pure HCC environment, if desired.  See this checkin:
https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/lib/extractkernel.in
You need to generate a full linked executable (not just object files) but then can use the tool above to extract all of the "code objects".
