### ISSUE TITLE
Unable Compile with error of "fatal error: 'amp.h' file not found"

### ISSUE THREAD

**Issue by smithakihide** [RadeonOpenCompute/hcc#135]
hello, I am exploring a HPC code by C++ AMP.

I am in trouble about building environment of HCC on Ubuntu, could you help me?
I am Japanese, sorry for my poor English.

summary, I couldn't compile this test case code by HCC packaged in rocm explained in this site.
here is the full code.
```
#include <iostream>
#include <amp.h>


int main()
{
    std::cout << "hello\n";
    return 0;
}
```
compile command is,
```hcc `hcc-config --cxxflags --ldflags` test.cpp```
then, this is outputted.
```test.cpp:3:10: fatal error: 'amp.h' file not found```
following terms are my environmental information.

CPU : corei5 6400
memory : DDR4 8GB
OS : Ubuntu 16.04 kernel = 4.4.0-kfd-compute-rocm-rel-1.2-31
GPU : R9 390
graphic driver : Radeon Pro GPU driver in the site of [here AMD's site](http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%e2%80%93Release-Notes.aspx)

I took below procedure,

1, Install Ubuntu 16.04 with option to install third party software and system update.
2, apt-get update,
3, Install ROCm Package with following [this site](https://github.com/RadeonOpenCompute/hcc/wiki) .
4, Install AMD driver above.
5, export PATH=$PATH:/opt/rocm/hcc/compiler/bin
6, compile test cord.

when i exclude  "amp.h", this cord run fine.

could I take some instructions?
thank you for reading.

**Comment by whchung** [comment]
could you show the result of `hcc-config --cxxflags` , and check if the path specified is really there?

**Comment by whchung** [comment]
Once you resolve the path inclusion issue, based on your hardware configuration (AMD R9 390), I would suggest you replace your compile command as:

```
hcc `hcc-config --cxxflags --ldflags` --amdgpu-target=AMD:AMDGPU:7:0:1 test.cpp
```

Reason for this is because by default hcc is configured to produce AMD GCN ISA codes for Fiji/Polaris cards with ISA version string "AMD:AMDGPU:8:0:3", and your GPU (AMD R9 390) is Hawaii with ISA version string "AMD:AMDGPU:7:0:1".

**Comment by smithakihide** [comment]
thank you for replying.

I excute  `hcc-config --cxxflags` , and got the output `hcc-config: command not found`

could you teach to me where should I set PATH to?

**Comment by smithakihide** [comment]
thank you suggestion.

I ' ll put it in mind to use the option of AMDGPU:7:0:1.

**Comment by whchung** [comment]
@smithakihide Looking at your original post, I think you set PATH incorrectly:

Your config:
```
export PATH=$PATH:/opt/rocm/hcc/compiler/bin
```
It should be:
```
export PATH=$PATH:/opt/rocm/hcc/bin
```

**Comment by smithakihide** [comment]
thank you,
I could compile my cord by setting `export PATH=$PATH:/opt/rocm/hcc/bin`

but , new problem occurred.

I execute 
```hcc `hcc-config --cxxflags --ldflags` --amdgpu-target=AMD:AMDGPU:7:0:1 test.cpp```
to compile and I could get a.out file.

then I execute a.out, and get this output,
```
CPU Node [0] has no GPU connected
There is no device can be used to do the computation
```

My knowledge is too narrow to understand this problem.
could you tell me why this occurred.

my clinfo output is here,
```
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (2117.7)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 2
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 
  Device Topology:				 PCI[ B#1, D#0, F#0 ]
  Max compute units:				 14
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 555Mhz
  Address bits:					 64
  Max memory allocation:			 4244635648
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 2048
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 7952171008
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 32768
  Max pipe arguments:				 0
  Max pipe active reservations:			 0
  Max pipe packet size:				 0
  Max global variable size:			 0
  Max global variable preferred total size:	 0
  Max read/write image args:			 0
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7feadca718f8
  Name:						 Hawaii
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 2117.7 (VM)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (2117.7)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 


  Device Type:					 CL_DEVICE_TYPE_CPU
  Vendor ID:					 1002h
  Board name:					 
  Max compute units:				 4
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 1024
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 8
  Preferred vector width double:		 4
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 8
  Native vector width double:			 4
  Max clock frequency:				 1054Mhz
  Address bits:					 64
  Max memory allocation:			 2147483648
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 8192
  Max image 2D height:				 8192
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 4096
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 32768
  Global memory size:				 7246921728
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Global
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2147483648
  Max global variable size:			 1879048192
  Max global variable preferred total size:	 1879048192
  Max read/write image args:			 64
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 1
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7feadca718f8
  Name:						 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
  Vendor:					 GenuineIntel
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 2117.7 (sse2,avx)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (2117.7)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event 

```
By the way , Is it better for me to create a new issue about this problem ?

i want to get a suggestion.

**Comment by whchung** [comment]
From your description it seems you already have ROCm stack installed. Could you check if ROCm stack is up & running on your system? You can follow instructions at: `https://github.com/RadeonOpenCompute/ROCm#verify-installation`

**Comment by smithakihide** [comment]
thank you for helping me.

yes,

I tried to verify follow  `https://github.com/RadeonOpenCompute/ROCm#verify-installation` now,
and got output this message.
``` 
CPU Node [0] has no GPU connected
Initializing the hsa runtime succeeded.
Checking finalizer 1.0 extension support succeeded.
Generating function table for finalizer succeeded.
Getting a gpu agent failed.
```
yes, I installed Radeon Pro GPU driver. I don't know that ROCm have own drive within.
The reason I installed Radeon Pro GPU Driver that ROCm GPU driver not work fine. when I tried boot using ROCm GPU driver by loading kernel 4.4.0-kfd-compute-rocm-rel-1.2-31, my desk top screen get white nose.
I also tried secure boot using ROCm kernel, and I can log in Console only UI.
I assume kernel is working well, but, driver is not. 

my motherboard model is Z170-SO1, OEM version.
I am happy if i could get your reply.

**Comment by smithakihide** [comment]
I tried to Uninstall Radeon Pro GPU driver. And boot using ROCm kernel.

As I knew it, the graphic driver within ROCm did not work well. I got noised desktop graphics.
then I log in console only. to press Alt + F1, it worked.

then I tried to compile the cord I mentioned in first comment of this topic, I could compile and execute the output file  exactly I expected.
I also tried to run the Matrix simulation cord, and it also work fine.
considering this fact, GPU calculation is not miss,

why graphics only get noise when I use ROCm kernel?. 

but, in this environment, I can't use GUI of Ubuntu.
help me.

**Comment by whchung** [comment]
@smithakihide I'm glad you are able to run GPGPU computation on ROCm stack now.

For corrupted graphics, I'm sorry I don't have the exact model of Hawaii-based GPU (R9 390) so I can't say. To my knowledge Fiji-based GPUs (ex: R9 Nano, R9 Fury X) don't suffer from this issue.

As this seems to be a kernel driver issue, I would recommend you post your information at: `https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/issues` so kernel developers may help you there. You may need to provide the following information:

- CPU model
- motherboard model
- GPU model
- `dmesg` log after you boot with ROCm 1.2 kernel

**Comment by smithakihide** [comment]
thank you, Mr. whchung. you are very helpful for me.
I managed to run GPGPU computation with help by you.

my computation score, compare  with  VS2015 on Win 10 with same hardware environment.
at the simple matrix calculation test.

VS2015 172[ms]
HCC   430[ms]

a bit slow....,

anyway, thank you very much.

I also post the rest problem about graphics to that site as you say.
