### ISSUE TITLE
Link hcc outfiles with external compilation units

### ISSUE THREAD

**Issue by szellmann** [RadeonOpenCompute/hcc#138]
Hi,

sorry for misusing the issue tracker for a mere question.

I'd like to link hcc-compiled compilation units with .o files that are generated with a different compiler and found no section in the docs where this is explained. I built the hcc .o with a command similar to `hcc `hcc-config --cxxflags` file.cpp -c -o file.o` and would now like to do linking with an "ordinary" host compiler so I can build a shared library from several external compilations units, and from `file.o`. Since only `file.o` contains "heterogeneous" code, I'd think that `-hc` does not need to end up on the linker command line, and that any linker can be used, am I right? In that case, what hcc libraries would I have to link in to make this work?

**Comment by whchung** [comment]
@szellmann mixing .o between HCC and other compilers won't work as of now, the reason is because there is a special section ".kernel" in every .o file produced by HCC. Inside is the LLVM bitcode for HCC kernels. At link-time, a special linker script in HCC will traverse ".kernel" sections among all object files, and produce either HSA BRIG, or AMD GCN ISA. Therefore, right now you have to use HCC as the linker, if you want to build a shared library, `hcc-config --shared` would produce relevant options.

**Comment by szellmann** [comment]
Thanks for the clarification. I will try if I can either build the entire application with hcc, or dynamically link the GPU code into my binary as a last resort.

Not sure if it is on your roadmap to relax this. I think in most cases one can make do with using hcc as the sole compiler since it's a clang anyway, but there are cases where it may be more convenient to have the option to use a linker from a different tool chain.

**Comment by Dekken** [comment]
I'm having a similar problem just using hcc over two commands rather than one

This works
hcc -o out $(hppconfig --cxxflags --ldflags) cpp.cpp

but this does not
hcc -o out.obj $(hppconfig --cxxflags) -c cpp.cpp
hcc -o out out.obj $(hppconfig --ldflags)

Is this correct?

**Comment by whchung** [comment]
@Dekken your 2-steps commands seem to be correct. could you post a reduced test case which reproduces the error you are seeing?

**Comment by Dekken** [comment]
The second command doesn't give an error, but no binary is created either.

I will post a minimal example later today.

**Comment by Dekken** [comment]
Minimal test case, which for me does not create a binary.

http://pastebin.com/raw/mD7KY1pu

**Comment by PhilipDeegan** [comment]
I get a segfault in that example so it might not be the best

**Comment by PhilipDeegan** [comment]
It appears the file type must be nothing other than ".o" for successful linking.

**Comment by david-salinas** [comment]
works with latest ROCm 1.9
