### ISSUE TITLE
Is hcc really deprecated?

### ISSUE THREAD

**Issue by heroxbd** [RadeonOpenCompute/hcc#1421]
Hi, I am from the Gentoo community and is trying to package the HIP ecosystem into Gentoo.  After reading hcc README.md, it was committed by @scchan [a year ago](https://github.com/RadeonOpenCompute/hcc/commit/e458d8ac32defb4877c973d24e2392c3913fda96) that hcc is deprecated.

But, as far as I know, HIP have 2 AMD backends, one is `roc-hcc` and the other is [roc-ocl](https://github.com/RadeonOpenCompute/llvm/releases). Confusingly, `roc-hcc` now has release 3.1.0, on par with HIP-3.1.0, but `roc-ocl` is still at release 2.10.0. 

Is hcc really deprecated?  @scchan himself have a lot of commits right up till now after his claim of deprecation of hcc (https://github.com/RadeonOpenCompute/hcc/commits?author=scchan&before=ff0ba6c81cdea0a7172604287bdfad752a3ee90d+35).  If I want to give Gentoo users future-proof HIP technology, which one should I prioritize for, deprecated but new `hcc` or non-deprecated but old `roc-ocl`?

Similar confusion has been documented at https://github.com/ROCm-Developer-Tools/HIP/issues/1196

**Comment by pfultz2** [comment]
Are you building hip-clang from source?

**Comment by heroxbd** [comment]
> Are you building hip-clang from source?

Yes we are, Gentoo is a Linux distribution that by default build everything in the OS from source.

**Comment by pfultz2** [comment]
Where are those build scripts? I am interested in building hip-clang in our CI.

**Comment by heroxbd** [comment]
> Where are those build scripts? I am interested in building hip-clang in our CI.

They are working-in-progress.  I will inform you when they are ready.

**Comment by heroxbd** [comment]
After investigation, hcc is deprecated and HIP-clang has upstreamed all the work to llvm.  Well done!

Reference: https://github.com/ROCm-Developer-Tools/HIP/commit/af697eaefed7806d1d561f9f5087f07f7013a4ec
