### ISSUE TITLE
-lm does not end up on the linker command line with hcc-config

### ISSUE THREAD

**Issue by szellmann** [RadeonOpenCompute/hcc#144]

**Comment by szellmann** [comment]
Sorry, accidentally submitted the issue w/o a description. I'm having the problem that with a command line like

```hcc `hcc-config --ldflags` ```

-lm does not end up on the command line so that when I have a program that uses math functions in the host program part it won't link. Adding ```-lm``` manually solves the issue but this is probably not the intended way to do since libm's implementation will probably not be used on the device, right?

So what is the right way to compile with hcc, I have a program that uses math functions on both host and device side?

**Comment by szellmann** [comment]
This can btw. reproduced nicely with the following really tiny program:

```C++
// main.cpp

#include <hcc/hc_math.hpp>
//#include <cmath>

int main()
{
    return (int)sqrtf(2.0f);
}
```

When calling

```hcc `hcc-config --cxxflags --ldflags` main.cpp```

the linker complains:

```/tmp/tmp.4WoGgeEz7y/hcc-5728f9.host.o: In function `main':
/tmp/hcc-ece2c5.s.bc:(.text+0x18): undefined reference to `sqrtf'```

while

```hcc `hcc-config --cxxflags --ldflags` hcc.cpp -lm```

compiles and links just fine.

BTW: Ubuntu 14.04

```$ lsb_release```

```LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch```

```$ uname -a```

```Linux XXXXXX 4.4.0-kfd-compute-rocm-rel-1.2-31 #1 SMP Fri Jul 22 06:06:24 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux```

```hcc --version```

```HCC clang version 3.5.0  (based on HCC 0.10.16313-d90738a-10704f4 LLVM 3.5.0svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix```

**Comment by whchung** [comment]
@szellmann normally it's anticipated that user would link with `-lm` if math functions are used in host codes. but as you mentioned, it could also be easier for users to rely on `hcc-config` to provide all the necessary linker flags. I'm wondering would you mind come up with a pull request? I'd love to accept it.
