### ISSUE TITLE
extractkernel for rdc code

### ISSUE THREAD

**Issue by brad-mengchi** [RadeonOpenCompute/hcc#1452]
Hi all,

I tried to write a __global__ kernel and a __device__ function and compile __device__ function in a relocatable way(-fgpu-rdc). Then I tried to use extractkernel script to dump the AMD GPU assembly code.

Seems that it fails to dump since there is no .hip_fatbin section after extracting(objdump -h) the executable. So does anyone know which section (names) extractkernel needs to recognize to dump GPU kernel assembly?

P.S.: I am using ROCm 4.0.0 with clang(llvm) 12.

Thanks!

**Comment by searlmc1** [comment]
+@david-salinas

**Comment by brad-mengchi** [comment]
Since hcc is no longer supported. I also move this question to https://github.com/ROCm-Developer-Tools/HIP/issues/2274.

**Comment by lamb-j** [comment]
https://github.com/ROCm/HIP/issues/2274 has been closed, so closing this as well
