### ISSUE TITLE
Linking two modules of different data layouts

### ISSUE THREAD

**Issue by PhilipDeegan** [RadeonOpenCompute/hcc#155]
After building clang_tot_upgrade and everything else from source, I get this warning, which doesnt' appear to cause any problems, but more unsightly than anything.
```
hcc -Wall $(hcc-config --cxxflags --ldflags) -Os -fPIC -I/opt/rocm/include -o saxpy  -Wl,--rpath=/opt/rocm/lib -L/opt/rocm/lib saxpy .cpp
WARNING: Linking two modules of different data layouts: '/tmp/tmp.WIU6ppDs60/hcc-83b52a.kernel.bc' is '' whereas 'llvm-link' is 'e-p:32:32-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64
```

**Comment by PhilipDeegan** [comment]
If you split it over two commands it doesn't complain though

```
hcc -Wall $(hcc-config --cxxflags) -Os -fPIC -I/opt/rocm/include -o saxpy.o -c hcc.cpp
hcc $(hcc-config --ldflags) -Wl,--rpath=/opt/rocm/lib -L/opt/rocm/lib -o saxpy saxpy.o
```

**Comment by psteinb** [comment]
I see this with rocm-1.5 as well. trying to compile a GPU memory bandwidth benchmark using this [Makefile](https://github.com/psteinb/GPU-STREAM/blob/rocm_hc_support/HC.make). 

```
$ make -B -f HC.make
hcc -O3 -hc -I/opt/rocm/hcc/include  -DHC main.cpp HCStream.cpp  -L/opt/rocm/hcc/lib -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive -ldl   -o hc-stream
WARNING: Linking two modules of different data layouts: '/tmp/tmp.mjEfWOVpd0/HCStream-717afc.kernel.bc' is '' whereas 'llvm-link' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
```

**Comment by psteinb** [comment]
If I used `hcc-config` in the Makefile, the error occurs as well:

```
$ make -B -f HC.make
hcc -O3 -hc  -hc -std=c++amp -I/opt/rocm/hcc-1.0/include  -DHC main.cpp HCStream.cpp   -hc -std=c++amp -L/opt/rocm/hcc-1.0/lib -Wl,--rpath=/opt/rocm/hcc-1.0/lib -ldl -lm -lpthread -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive   -o hc-stream
WARNING: Linking two modules of different data layouts: '/tmp/tmp.S093oZ3iAG/HCStream-da8660.kernel.bc' is '' whereas 'llvm-link' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:64:64-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64'
```

the produced binary appears to work perfectly though.

**Comment by whchung** [comment]
@psteinb I'm suspecting `HCStream.cpp` doesn't contain actual kernels, right? due to recent changes in the compiler frontend, less bitcodes, even empty bitcode, would be produced by the frontend in case the translation unit contains no kernels. Therefore this warning message may arise at link time.

**Comment by psteinb** [comment]
[HCStream.cpp](https://github.com/psteinb/GPU-STREAM/blob/rocm_hc_support/HCStream.cpp) does 
contain kernels.

**Comment by alephpt** [comment]
is there a solution to this?

**Comment by misyntropy** [comment]
What was the solution, I get these messages even now for ROCm 6.

**Comment by PhilipDeegan** [comment]
@milindsmart hcc as a compiler is no longer maintained. you should switch to hipcc

**Comment by misyntropy** [comment]
I'm using the latest ROCm HIPcc 6.0.2 on Fedora 40, trying to compile ROCm-examples. 

I get multiple messages that look like 

> warning: Linking two modules of different data layouts: '/usr/lib64/llvm17/bin/../../../lib/clang/17/amdgcn/bitcode/oclc_isa_version_900.bc' is 'e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8' whereas 'main_gfx900.ll' is 'e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9-p9:192:256:256:32'

... with varying filenames in the first entry.
