### ISSUE TITLE
How to use  hcc_hsail in Rocm 1.3

### ISSUE THREAD

**Issue by bshaozi** [RadeonOpenCompute/hcc#170]
I had compiled my code successful and run correctly  in rocm 1.2 envrionment(Kaveri).
 But after I update the rocm to 1.3, I found it seems the hcc_hsail had been deprecated. 
So, I use '/opt/rocm/hcc/' instead of `/opt/rocm/hcc-hsail/`. (for instance , use /opt/rocm/hcc/bin/hcc `/opt/rocm/hcc/bin/hcc-config --cxxflags  --ldflags`  -I /opt/rocm/hcc/include/ xxx.cpp -o xxx  to compile). It compiles successful.
But it returns error when running.follows is the error information.
### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS (0x100d) at file:/home/scchan/code/github/radeonopencompute/hcc.1.3/hcc/lib/hsa/mcwamp_hsa.cpp line:2504
Abortado (`core' generado)

How can I compile my code  in  Kaveri envrionment with rocm 1.3?

**Comment by whchung** [comment]
could you try add "--amdgpu-target=AMD:AMDGPU:8:0:1" in your compile option? The default compiler backend now generates GCN instructions instead of HSAIL by default, and `--amdgpu-target=` let's you specify GCN ISA for your APU or dGPU.

**Comment by bshaozi** [comment]
Thank you for the reply. I had added the '--amdgpu-target=AMD:AMDGPU:8:0:1' in  my compile option.  But when I run the program, it still  crash and return error information as follows:

### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS (0x100d) at file:/home/scchan/code/github/radeonopencompute/hcc.1.3/hcc/lib/hsa/mcwamp_hsa.cpp line:2504

Aborted (core dumped)

Follows is my compile command(in ROCM 1.3) ,it doesn't work:
/opt/rocm/hcc/bin/hcc   `/opt/rocm/hcc/bin/hcc-config --cxxflags  --ldflags`  --amdgpu-target=AMD:AMDGPU:8:0:1    xxx.cpp -o xxx

Before I update ROCM to 1.3. My compile command as follows and it works well:
/opt/rocm/hcc-hsail/bin/hcc   `/opt/rocm/hcc-hsail/bin/hcc-config --cxxflags  --ldflags`  -I /opt/rocm/hcc-hsail/include/ xxx.cpp  -o xxx

What should I do to fix it?

Thanks.

haochen@multicorewareinc.com

From: Wen-Heng (Jack) Chung
Date: 2016-11-19 02:23
To: RadeonOpenCompute/hcc
CC: bshaozi; Author
Subject: Re: [RadeonOpenCompute/hcc] How to use hcc_hsail in Rocm 1.3 (#170)
could you try add "--amdgpu-target=AMD:AMDGPU:8:0:1" in your compile option? The default compiler backend now generates GCN instructions instead of HSAIL by default, and --amdgpu-target= let's you specify GCN ISA for your APU or dGPU.

**Comment by bshaozi** [comment]
I add  '--amdgpu-target=AMD:AMDGPU:7:0:0'  instead of '--amdgpu-target=AMD:AMDGPU:8:0:1.
It works fine.

Thanks again!
