### ISSUE TITLE
CPU Node [0] has no GPU connected

### ISSUE THREAD

**Issue by PhilipDeegan** [RadeonOpenCompute/hcc#172]
First, congratulations on the 1.3 release.

Not sure what you did but my GNOME openbox desktop is working again.

Using the new 4.6 kernel, and much the same setup as the 1.2 setup for clang_tot_upgrade branch, I am having difficulty running the saxpy example.

hcc $(hcc-config --ldflags --cxxflags)  -o sax saxpy.cpp -g3
LD_LIBRARY_PATH=/opt/rocm/lib ./sax
CPU Node [0] has no GPU connected
Segmentation fault

**Comment by aditya4d** [comment]
Can you try running hsa sample in /opt/rocm/hsa/sample ?

**Comment by PhilipDeegan** [comment]
LD_LIBRARY_PATH=/opt/rocm/lib ./vector_copy
CPU Node [0] has no GPU connected
Segmentation fault

**Comment by aditya4d** [comment]
Can you paste in uname -a ?

**Comment by PhilipDeegan** [comment]
uname -a
Linux toast 4.6.0-kfd #1 SMP Sat Nov 19 19:04:45 GMT 2016 x86_64 GNU/Linux

**Comment by aditya4d** [comment]
Seems like a runtime issue. Can you create an issue here[1]?
[1]. https://github.com/RadeonOpenCompute/ROCR-Runtime/issues

**Comment by scchan** [comment]
@Dekken 

Looks like you didn't install the kernel from AMD?  Mine shows:

Linux d7e13bb11ac9 4.6.0-kfd-compute-rocm-rel-1.3-63 #1 SMP Fri Oct 28 13:14:45 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by PhilipDeegan** [comment]
I built https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/tree/roc-1.3.x so I would imagine it's right.

**Comment by scchan** [comment]
I don't think this is related to the hcc compiler at this point.  Do you mind opening a ticket against RadeonOpenCompute/ROCm so that the driver and runtime guys could respond to it?  Thanks.

**Comment by PhilipDeegan** [comment]
I've already opened up a ticket on runtime, rather not be spamming tickets tbh

**Comment by scchan** [comment]
to be investigated by the runtime  https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/17
