### ISSUE TITLE
Supported Platform Clarification?

### ISSUE THREAD

**Issue by ghost** [RadeonOpenCompute/hcc#173]
I know this is horribly pedantic, but I will have to buy a CPU & board to play with a Polaris card and HCC, my dev box is a Sandy Bridge. If I must buy Intel I would prefer to buy a low price i3 or Pentium instead of an expensive i5 or i7. And, I'm sort of waiting for Zen...

The HCC page at gpuopen says:

"Discrete GPU system support
CPU: Intel Haswell or Newer, Core™ i5, Core™ i7; Xeon® E3 v4 & v5; Xeon® E5 v3"

The HCC wiki page says:

"... Radeon discrete GPUs from the Fiji family ... paired with an Intel Haswell CPU or newer."

Two questions: 

1) Will the HCC stack work on an Haswell/Broadwell/Skylake i3 or Pentium?
2) Will it work on Zen?

**Comment by whchung** [comment]
@emerth ROCm stack requires processors which support PCIe Gen 3 atomic operations. I've not personally checked i3 or Pentium before. Zen will be supported.

**Comment by ghost** [comment]
Thanks whchung! I will research that.
