### ISSUE TITLE
How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？

### ISSUE THREAD

**Issue by bshaozi** [RadeonOpenCompute/hcc#186]
There is some problem  in my KAVERI environment after I update rocm to 1.3.
So I want to re-isntall rocm-1.2 in my environment,  what should I do? 
I had tried 'sudo apt-get install rocm=1.2' ,but  failed.
BTW, my system is ubuntu 14.04.

Thanks.

**Comment by whchung** [comment]
@jedwards-AMD could we post 1.2 packages on `packages.amd.com` incase users want to downgrade?

**Comment by bshaozi** [comment]
Yes. That's great if we can download the 1.2 from source.

Now, there is only 1.3.1, but it is not suitable for KAVERI.

Package: rocm
Source: AMD
Maintainer: James Edwards (JamesAdrian.Edwards@amd.com)
Homepage: https://github.com/RadeonOpenCompute/ROCm 
Version: 1.3.1
Architecture: amd64
Depends: rocm-dev (=1.3.1), rocm-kernel (=1.3.1), rocm-profiler (=4.0.6036)
Priority: extra
Section: devel
Filename: pool/main/A/AMD/rocm_1.3.1_amd64.deb
Size: 1636
SHA256: 14248d7dc2a7271558e4871d41af4b14201f599c2cfa832d18416645617c0820
SHA1: 2916210bcfddb859f2538606fe113da0ec3df589
MD5sum: a70cc2814ef1465d0f5439728598c53a
Description: Radeon Open Compute (ROCm) Runtime software stack
Description-md5: 6a6a8f854ad10a9802b980cf99b587d2



haochen@multicorewareinc.com
 
发件人： Wen-Heng (Jack) Chung
发送时间： 2016-12-08 10:10
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Author
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
@jedwards-AMD could we post 1.2 packages on packages.amd.com incase users want to downgrade?

**Comment by bshaozi** [comment]
There is any update?


Thanks.


haochen@multicorewareinc.com
 
发件人： Wen-Heng (Jack) Chung
发送时间： 2016-12-08 10:10
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Author
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
@jedwards-AMD could we post 1.2 packages on packages.amd.com incase users want to downgrade?
―

**Comment by bshaozi** [comment]
Can  I  get  ROCm-1.2 from the packages.amd.com now???



haochen@multicorewareinc.com
 
发件人： Wen-Heng (Jack) Chung
发送时间： 2016-12-08 10:10
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Author
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
@jedwards-AMD could we post 1.2 packages on packages.amd.com incase users want to downgrade?

**Comment by jedwards-AMD** [comment]
You can find the old repository for ROCm 1.2 here:

http://packages.amd.com/rocm/gz/rocm_1.2-debian-repo.tar.gz

**Comment by bshaozi** [comment]
Thanks for reply.
Can I  use 'sudo apt-get install rocm=1.2' to auto install the 1.2 version?  Just like I  install it(before update to 1.3 version) before?


Thanks.


haochen@multicorewareinc.com
 
发件人： James Edwards
发送时间： 2016-12-13 00:27
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Comment
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
You can find the old repository for ROCm 1.2 here:
http://packages.amd.com/rocm/gz/rocm_1.2-debian-repo.tar.gz

**Comment by jedwards-AMD** [comment]
No, we archive the old releases. If you want to install 1.2 you have to download the archived repo and use the method I suggested.

**Comment by bshaozi** [comment]
Hi.

I can;t download the 'rocm_1.2-debian-repo.tar.gz' from  'http://packages.amd.com/rocm/gz/rocm_1.2-debian-repo.tar.gz', is there any other source for downloading?



haochen@multicorewareinc.com
 
发件人： James Edwards
发送时间： 2016-12-13 09:19
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Comment
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
No, we archive the old releases. If you want to install 1.2 you have to download the archived repo and use the method I suggested.

**Comment by whchung** [comment]
@bshaozi could you let me know what error you are seeing downloading the archive?

**Comment by jedwards-AMD** [comment]
Also, try this command: 'wget http://packages.amd.com/rocm/gz/rocm_1.2-debian-repo.tar.gz'

**Comment by bshaozi** [comment]
Thanks reply. It has been downloading. But it will cost several hours.

Can you give me some detail  information about how to install rocm1.2  from this  archived file? 



haochen@multicorewareinc.com
 
发件人： James Edwards
发送时间： 2016-12-16 23:53
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Mention
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
Also, try this command: 'wget http://packages.amd.com/rocm/gz/rocm_1.2-debian-repo.tar.gz'

**Comment by whchung** [comment]
In the archive it contains all the debian packages. So you should be able to install them via normal `dpkg -i`.

**Comment by bshaozi** [comment]
Thanks for your reply.

I had added this packages to my local software soure ,and install it via apt-get install.
But there is another problem.  Because I had updated rocm  to 1.3 before ,and now linux kernel is "4.6.0-kfd-compute-rocm-rel-1.3-63" although I had removed romc1.3 and install rocm1.2 again.

How can I resotre the kernel to rocm1.2?

Thanks


haochen@multicorewareinc.com
 
发件人： Wen-Heng (Jack) Chung
发送时间： 2016-12-19 11:59
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Mention
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
In the archive it contains all the debian packages. So you should be able to install them via normal dpkg -i.

**Comment by whchung** [comment]
@bshaozi you should be able to install 1.2 packages with `dpkg -i`, and you may need to edit your grub configuration to pick `4.4.0-kfd-compute-rocm-rel-1.2-31` as your default kernel.

**Comment by jedwards-AMD** [comment]
You have to manually uninstall kernel packages; apt-get will not uninstall them. Executing 'dpkg -r <kernel package name>' will take care of it. The 1.2 kernel package should still be installed, and should become your default boot image.

**Comment by bshaozi** [comment]
Thanks. I had changed the default kernel image to rocm1.2 via edited grub file ,rocm1.2 kernel is loaded in my KAVERI.
Thanks agian! 



haochen@multicorewareinc.com
 
发件人： James Edwards
发送时间： 2016-12-19 23:09
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Mention
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
You have to manually uninstall kernel packages; apt-get will not uninstall them. Executing 'dpkg -r ' will take care of it. The 1.2 kernel package should still be installed, and should become your default boot image.

**Comment by bshaozi** [comment]
Thanks. I had changed the default kernel image to rocm1.2 via edited grub file ,rocm1.2 kernel is loaded in my KAVERI.
Thanks agian! 



haochen@multicorewareinc.com
 
发件人： Wen-Heng (Jack) Chung
发送时间： 2016-12-19 18:13
收件人： RadeonOpenCompute/hcc
抄送： bshaozi; Mention
主题： Re: [RadeonOpenCompute/hcc] How to re-install 1.2 after update to 1.3 in KAVERI with ubuntu 14.04？ (#186)
@bshaozi you should be able to install 1.2 packages with dpkg -i, and you may need to edit your grub configuration to pick 4.4.0-kfd-compute-rocm-rel-1.2-31 as your default kernel.
