### ISSUE TITLE
Runtime crash on APU when using HCC compiler

### ISSUE THREAD

**Issue by vanceNyriad** [RadeonOpenCompute/hcc#187]
Ubuntu VERSION="16.04.1 LTS (Xenial Xerus)"
AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G
Attempting to compile and run the saxpy code found at: https://gist.github.com/scchan/540d410456e3e2682dbf018d3c179008 saved in a file called hcctestfile.cpp
Compiling using : hcc `hcc-config --cxxflags --ldflags` hcctestfile.cpp -o test && ./test
compiles successfully but when run produces: HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS (0x100d) at file:/home/scchan/code/github/radeonopencompute/hcc.1.3/hcc/lib/hsa/mcwamp_hsa.cpp line:2504 Aborted (core dumped)
I have tried adding: --amdgpu-target=AMD:AMDGPU:7:0:1 or --amdgpu-target=AMD:AMDGPU:8:0:1
resulting in the same error

The code compiles and runs correctly on a different pc with a discrete gpu: Fiji [Radeon R9 FURY / NANO Series]

![errormessage](https://cloud.githubusercontent.com/assets/24465903/21033252/1df165b2-be14-11e6-97ef-2a1f402fb427.png)

**Comment by whchung** [comment]
@vanceNyriad can you try "--amdgpu-target=AMD:AMDGPU:7:0:0"?

**Comment by vanceNyriad** [comment]
@whchung it has run succesfully
