### ISSUE TITLE
Executing the binaries generated by the HCC-Example-Application Segfaults

### ISSUE THREAD

**Issue by utopiabhsg** [RadeonOpenCompute/hcc#203]
I have APU Carrizo environment (AMD Embedded R-Series RX-421BD Radeon R7 SOC board) and im running Ubuntu 16.04 on it. Installed ROCm 1.4 and ran vector_copy sample, got all success messages. I git cloned HCC-Example-Application repository on my system built all the example samples and executing the ArrayBandwidth and HCFFT binaries gave the correct output. But when i try to execute MD, SPMV and SyncVsAsyncArrayCopy binaries it Segfaults with core dumped. Also, when i try to re execute the binaries ArrayBandwidth and HCFFT(which previously gave the output) segfaults with the same message.
Are there any steps I'm missing or should be doing in order to execute all the binaries successfully? I'm a newbie to HSA programming domain. So any help is much appreciated. 

Thanks in advance!
bhsomegowda

**Comment by PhilipDeegan** [comment]
Are you running with 

```
LD_LIBRARY_PATH=/opt/rocm/lib ./binary
```

And if not, could you try that?

Following on please post the 

results of 

```
ldd ./binary
```

If you have debug symbols please also post the stack trace.

**Comment by PhilipDeegan** [comment]
Have a look at this https://github.com/RadeonOpenCompute/hcc/issues/197

**Comment by utopiabhsg** [comment]
Hi,
Im trying to complie saxpy.cpp example (All HCC applications segfaults)
I have linked '--amdgpu-target=AMD:AMDGPU:8:0:1' in the complie options. Here are my env variables:
> echo $PATH
/opt/rocm/bin:/opt/rocm/hcc/bin:/home/saa/bin:/home/saa/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>echo $LD_LIBRARY_PATH
>/opt/rocm/lib ./saxpy

Results of ldd ./saxpy:
>ldd ./saxpy
	linux-vdso.so.1 =>  (0x00007fff64b89000)
	libc++.so.1 => /usr/lib/x86_64-linux-gnu/libc++.so.1 (0x00007f3e3db86000)
	libc++abi.so.1 => /usr/lib/x86_64-linux-gnu/libc++abi.so.1 (0x00007f3e3d936000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3e3d72e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3e3d50e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3e3d2f6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3e3cf26000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3e3cd1e000)
	/lib64/ld-linux-x86-64.so.2 (0x0000561f0036a000)

There were no debugging symbols found to post the stack trace.
Let me know i have to provide further information. 

Thank you

**Comment by PhilipDeegan** [comment]
Your LD_LIBRARY_PATH should be set like this

```
export LD_LIBRARY_PATH="/opt/rocm/lib"
```

You appear to have included the binary in the export which I think makes the variable invalid. I have had numerous segfaults with the saxpy example, but it works for me at the moment when the LD_LIBRARY_PATH has visibility of the hsa-runtime(64).so

Can youi also do a 

```
ls -l /opt/rocm/lib
```

just to confirm you have the hsa runtime library?

Thanks

**Comment by utopiabhsg** [comment]
So i just set export LD_LIBRARY_PATH=/opt/rocm/lib in my .bashrc file
>echo $LD_LIBRARY_PATH
/opt/rocm/lib

./saxpy still segfaults.

I believe i do hsa runtime library!
Results of ls -l /opt/rocm/lib:
total 4
lrwxrwxrwx 1 root root 27 Dec 21 12:23 hip_ir.ll -> /opt/rocm/hip/lib/hip_ir.ll
lrwxrwxrwx 1 root root 64 Nov 11 15:34 libCXLActivityLogger.so -> ../profiler/CXLActivityLogger/bin/x86_64/libCXLActivityLogger.so
lrwxrwxrwx 1 root root 29 Dec 21 12:23 libhc_am.so -> /opt/rocm/hcc/lib/libhc_am.so
lrwxrwxrwx 1 root root 33 Dec 21 12:23 libhip_device.a -> /opt/rocm/hip/lib/libhip_device.a
lrwxrwxrwx 1 root root 31 Dec 21 12:23 libhip_hcc.so -> /opt/rocm/hip/lib/libhip_hcc.so
lrwxrwxrwx 1 root root 37 Dec 21 12:23 libhip_hcc_static.a -> /opt/rocm/hip/lib/libhip_hcc_static.a
lrwxrwxrwx 1 root root 31 Dec  2 14:24 libhsakmt.so -> ../libhsakmt/lib/libhsakmt.so.1
lrwxrwxrwx 1 root root 32 Dec  7 20:14 libhsa-runtime64.so -> ../hsa/lib/libhsa-runtime64.so.1
lrwxrwxrwx 1 root root 29 Dec 21 12:23 libmcwamp.a -> /opt/rocm/hcc/lib/libmcwamp.a
lrwxrwxrwx 1 root root 36 Dec 21 12:23 libmcwamp_atomic.a -> /opt/rocm/hcc/lib/libmcwamp_atomic.a
lrwxrwxrwx 1 root root 34 Dec 21 12:23 libmcwamp_cpu.so -> /opt/rocm/hcc/lib/libmcwamp_cpu.so
lrwxrwxrwx 1 root root 34 Dec 21 12:23 libmcwamp_hsa.so -> /opt/rocm/hcc/lib/libmcwamp_hsa.so

Thanks

**Comment by PhilipDeegan** [comment]
Can you show me the entire command you used to compile the saxpy example?

And can you confirm that the symlink is valid for /opt/rocm/lib/libhsa-runtime64.so (I'm assuming it is but just to be sure)

**Comment by utopiabhsg** [comment]
i tried the below 2 ways to compile the saxpy example:
* hcc `hcc-config --cxxflags --ldflags` --amdgpu-target=AMD:AMDGPU:8:0:1 saxpy.cpp -o saxpy
* hcc `hcc-config --cxxflags` saxpy.cpp -c -o saxpy.cpp.o
   hcc `hcc-config --ldflags` --amdgpu-target=AMD:AMDGPU:8:0:1 saxpy.cpp.o -o saxpy

Also to confirm the symlink, i typed 'readlink -f /opt/rocm/lib/libhsa-runtime64.so' on the terminal and got the following result,
>readlink -f /opt/rocm/lib/libhsa-runtime64.so
/opt/rocm/hsa/lib/libhsa-runtime64.so.1.1.1

**Comment by utopiabhsg** [comment]
PS: i did put hcc-config --cxxflags --ldflags , hcc-config --cxxflags , hcc-config --ldflags in between the two backticks.

**Comment by PhilipDeegan** [comment]
Yeah I figured, for sake of sanity consider using the following in future ;)

```
hcc $(hcc-config --cxxflags --ldflags)
```

I'm stumped, if you're interested in compiling (I have outstanding issues currently preventing me) with debug symbols you can attempt to use the following [script](https://github.com/lxcy/2.0.5-x86_64-debian8.6_hcc/blob/master/setup/rocm_master_dbg.sh) I have put together.

**Comment by utopiabhsg** [comment]
I compiled saxpy like so:
>hcc $(hcc-config --cxxflags --ldflags) --amdgpu-target=AMD:AMDGPU:8:0:1 saxpy.cpp -o saxpy

executing ./saxpy is still segfaulting.
What am i missing?
I'm happy to provide any information regarding my system/environment.
Running the executable through gdb says i do not have any debug symbols.

**Comment by PhilipDeegan** [comment]
You'll likely have to wait for one of the actual maintainers to respond, sorry.

**Comment by utopiabhsg** [comment]
Thanks @Dekken.

**Comment by aditya4d** [comment]
Hi,
Sorry to say this, Merlin Falcon boards are not supported by ROCm yet. Please find relevant information here: https://radeonopencompute.github.io/install.html

**Comment by vrajeshlm** [comment]
@bhsomegowda  will you pls help me to get some sample input and way to execute those ArrayBandwidth and HCFFT code because when i do it i am getting following error:

```
### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INCOMPATIBLE_ARGUMENTS (0x100d) at file:/home/scchan/code/github/hcc-roc-1.4.x/hcc/lib/hsa/mcwamp_hsa.cpp line:2511
Aborted (core dumped)

```

and it is refering to a file which doesnt even exist on machine.
