### ISSUE TITLE
Compile error when -Werror, -Wreorder enabled

### ISSUE THREAD

**Issue by syifan** [RadeonOpenCompute/hcc#236]
I got the following error if -Werror -Wall enabled. I am not sure if it is my mistake or some potential problem in HCC. Although I can use -Wno-reorder to disable the error detection, I think it is better to get rid of this problem, since it should be a very easy fix. 

```
/opt/rocm/hcc-lc/include/kalmar_runtime.h:95:47: error: field 'seqNum' will be initialized after field 'commandKind' [-Werror,-Wreorder]
  KalmarAsyncOp(hcCommandKind xCommandKind) : seqNum(0), commandKind(xCommandKind) {} 
```

**Comment by whchung** [comment]
@syifan this was fixed a while ago in this commit

https://github.com/RadeonOpenCompute/hcc/commit/10a2a89fbffd0e2e08da31c203cdaa5cfe59af3b#diff-fd44e4acc497ae0c856f2e116d5fe4c1

could you try pull a newer version of HCC?
