### ISSUE TITLE
Run a Sample HCFFT ?

### ISSUE THREAD

**Issue by VishwasRao17** [RadeonOpenCompute/hcc#246]
How to run a sample HCC FFT script or any HCC sample code?

**Comment by psteinb** [comment]
just out of curiosity, the instructions at the bottom of
https://bitbucket.org/multicoreware/hcfft
don't work for you?

**Comment by VishwasRao17** [comment]
@psteinb No, we tried it and we were getting error. We installed ROCm on AMD 7860K APU, then we followed instructions in the Bit bucket, but we got some runtime issues . So I was confused with the steps I was doing wrong.

**Comment by whchung** [comment]
@VishwasRao17 A10-7860K uses a different ISA version (7:0:0) than the default one (8:0:3). Could you try build HCFFT with an extra flag `--amdgpu-target=gfx700`?

**Comment by VishwasRao17** [comment]
@whchung Sure, I will check that and let you know. Thank you. 
By the way, the A10-7860K is well supported by ROCM and HCC right. I mean from Hardware perspective

**Comment by whchung** [comment]
From compiler perspective HCC is able to produce ISA for A10-7860K. But some OS & runtime-level features may not be present on Kaveri architecture, so we don't claim it's fully supported now. For more information please refer to: `https://github.com/RadeonOpenCompute/ROCm#are-you-ready-to-rock` .

**Comment by VishwasRao17** [comment]
@whchung Thank you, but in ROCM Kernel Driver we see tested HW platform is found to be 
The following is a reference hardware configuration that was used for testing purposes:

APU Config:
•APU: AMD A10-7850K APU
•Motherboard: ASUS A88X-PRO motherboard (ATX form factor)
•Memory: G.SKILL Ripjaws X Series 16GB (2 x 8GB) 240-Pin DDR3 SDRAM DDR3 2133
•OS: Ubuntu 14.04 64-bit edition
•No discrete GPU present in the system

 "https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/tree/roc-1.4.0" 

So I had bought this system for development.

**Comment by vrajeshlm** [comment]
@whchung me and @VishwasRao17 has done the ROCm installation and testing of vector_copy example to test if it is installed properly is successful. now we want to compile hcfft_1D_R2C.cpp as shown in https://bitbucket.org/multicoreware/hcfft/src and compilation is successful using following command 
**/opt/rocm/hcc/bin/clang++ `/opt/rocm/hcc/bin/hcc-config --cxxflags --ldflags`  -lhc_am -L/opt/rocm/hcfft/lib -lhcfft hcfft_1D_R2C.cpp -o hcfft_1D_R2C.out**
and when i try to execute it we get following error:
**No suitable runtime detected. Fall back to CPU!
Segmentation fault (core dumped)**

•APU used AMD A10-7850K APU for above experiment.

**Comment by whchung** [comment]
@vrajeshlm could you let me know the following information:

- Linux distro version
- `g++ --version`
- `/opt/rocm/hcc/bin/clang++ --version`
- `/opt/rocm/hip/bin/hipconfig`

I would also recommend you open an ticket at HCFFT site, as it seems to be a library issues instead of a compiler issue.

**Comment by vrajeshlm** [comment]
@whchung  
- Linux Distro version: Ubuntu 16.04 64 bit   (Ubuntu 16.04.4 64 bit)
- g++ --version: 5.4.0
- /opt/rocm/hcc/bin/clang++ --version: HCC clang version 3.5.0  (based on HCC 0.10.16501-81f0a2f-02246a0 LLVM 3.5.0svn) ... Target: x86_64-unknown-linux-gnu ... Thread model: posix

**Comment by whchung** [comment]
The configuration seem pretty normal. I do recommend you open a ticket at HCFFT site, as to my understanding, HCFFT would invoke extra HCC instances on-the-fly to generate FFT kernels. And perhaps in its implementation it doesn't pass `--amdgpu-target=gfx700` to HCC.

**Comment by vrajeshlm** [comment]
@whchung i tried using --amdgpu-target=gfx700 option using following command:
/opt/rocm/hcc/bin/hcc `/opt/rocm/hcc/bin/hcc-config --cxxflags --ldflags` **--amdgpu-target=gfx700** -lhc_am -lhcfft hcfft_1D_R2C.cpp 
i get warning:  -amdgpu-target argument 'gfx700' is not recognized, using fiji instead
i hope this is fine but still i am getting no suitable runtime detected. fall back to cpu!

**Comment by whchung** [comment]
@vrajeshlm unfortunately if you see the warning then it's not fine. Fiji is of ISA version 8:0:3, but A10-7850K is based on Kaveri which is of ISA version 7:0:0.

As a first step we need to get rid of this warning message, could you try replace the flag with `--amdgpu-target=AMD:AMDGPU:7:0:0` ? That was the old (now obsolete) syntax to specify ISA version for the compiler. I assume you are using stock HCC from ROCm 1.4 installation so that may be why "gfx700" doesn't work for you.

If you are past the compile-time warning, the next step is to fix the runtime error. I may need more information about when the error is raised when you run the executable to help determine whether it's an ROCR/HSA runtime issue, an HCC language runtime issue, or an HCFFT library issue.

To help isolate the issue, please first use this HCC unit test:
https://github.com/RadeonOpenCompute/hcc/blob/roc-1.4.x/tests/Unit/HC/reduction_hc.cpp

compile it with:

```
/opt/rocm/hcc/bin/clang `/opt/rocm/hcc/bin/hcc-config --cxxflags --ldflags` --amdgpu-target=AMD:AMDGPU:7:0:0 reduction_hc.cpp
```

and see if it runs. If it does run, then it's more likely an HCFFT issue.

**Comment by vrajeshlm** [comment]
@whchung as per your guidance I tried reduction_hc.cpp and it compiled and runs fine. 
following is the output of reduction_hc.cpp program which shows it is detecting amdgpu  gfx7000:
Using device : AMD HSA Agent gfx7000
Running kernels...
SUCCESS: sequential_reduction.
SUCCESS: reduction_simple_1.
SUCCESS: reduction_simple_2.
SUCCESS: reduction_tiled_1.
SUCCESS: reduction_tiled_2.
SUCCESS: reduction_tiled_3.
SUCCESS: reduction_tiled_4.
SUCCESS: reduction_cascade.

according to this it looks more like Hcfft issue. we will raise the query on HCFFT website.

thanks for your help. If you suggest us on any other installation related checks, then it will be really good for us.

**Comment by gstoner** [comment]
A10-7860K is not officially supported Processor in ROCm, please refer to the officially supported hardware section at https://rocm.github.io/hardware.html. 

I will get the Readme corrected 

Best regards 

G

**Comment by vrajeshlm** [comment]
@whchung is there any way to declare this amdgpu hcc compiler flag as a variable which will be taken care for any further compilation as I have many dependent files and libraries to compile.
