### ISSUE TITLE
HCC Sources Compatible with ROCM_1.4

### ISSUE THREAD

**Issue by vrajeshlm** [RadeonOpenCompute/hcc#282]
I just tried latest HCC repository branch = clang_tot_upgrade  but those sources are not compatible with ROCM_1.4. Hence I also tried branch = rocm_1.4.x of HCC and compiled but whenever I try to compile any program from it, gives me error as following :

```
/home/vrajesh/PIM_14.04/hcc_git/rocm_1.4/build/compiler/bin/clamp-link: line 63: [: -eq: unary operator expected
WARNING: Missing HSA toolchain.  Disable HSA target.
ERROR: No GPU target available! Linker failed.
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by whchung** [comment]
@vrajeshlm `clang_tot_upgrade` branch is compatible ROCm 1.4 and is the recommended branch to use because it's the most actively maintained one. could you share what difficulty you encountered?

**Comment by vrajeshlm** [comment]
the source of hc_am.hpp file doesn't match with hc_am.hpp source which we get by installing rocm from AMD PPA.
For Ex: I am trying to use hc::am_alloc() function and there it says  _allocSeqNum(0) undefined for AmPointerInfo class.

so looks like there might be such more changes which makes it incompatible with rocm 1.4

**Comment by whchung** [comment]
I would recommend follow steps at: `https://github.com/RadeonOpenCompute/hcc#download-hcc` and do a fresh clone of HCC, and build from source. Once the build is complete, `sudo make install` to replace what's installed from stock ROCm 1.4 distribution.

**Comment by vrajeshlm** [comment]
Hi @whchung I compiled latest HCC sources as per your guidance and used 
```
cmake -DNUM_BUILD_THREADS=96 \
      -DCMAKE_BUILD_TYPE=Release \
      ..
make
```
to compile it
after installation of this compiled sources whenever I try to compile any code it gives me following warning:
**'AMD:AMDGPU:7:0:0' is not a recognized processor for this target (ignoring processor)**

and runtime error :
```
### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INVALID_ISA_NAME (0x1017) at file:/home/scchan/code/github/hcc-roc-1.4.x/hcc/lib/hsa/mcwamp_hsa.cpp line:2115
Aborted (core dumped)
```

I am using   export HCC_AMDGPU_TARGET=AMD:AMDGPU:7:0:0 to specify gpu info.


and if I don't specify AMDGPU_TARGET then compilation works without such warning but at run time I get following error:
```
### HCC RUNTIME ERROR: Fail to find compatible kernel at File:/home/vrajesh/PIM_14.04/hcc_git/hcc/lib/mcwamp.cpp line:344

```

**Comment by whchung** [comment]
@vrajeshim I think you are using hardware not supported by ROCm. Please check https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md for supported hardware.

**Comment by vrajeshlm** [comment]
Hi @whchung I am using AMD APU A10-7860 and it says it has some limited support. . Is there any way to add some code to make it working because we(@Samsung_India) would like to contribute to ROCm.

**Comment by whchung** [comment]
@vrajeshlm Please contact @gstoner for more information wrt reviving Kaveri support. I think we can take this discussion offline.

**Comment by vrajeshlm** [comment]
@whchung  will you pls help me to get @gstoner 's Email id to take this discussion offline. I tried but I couldn't get it.

**Comment by whchung** [comment]
@vrajeshlm please shoot me an email first, you can find my address on my personal profile.
