### ISSUE TITLE
Status of c++ amp on linux?

### ISSUE THREAD

**Issue by gsedej** [RadeonOpenCompute/hcc#338]
Hi,
I was just checking the status of hcc c++amp for amd hardware on linux ubuntu 16.04 using rocm packages (https://github.com/RadeonOpenCompute/ROCm)

The 'hcc `clamp-config --build --cxxflags --ldflags` ampTest.cpp' does not work. When executing 'clamp-config --build --cxxflags --ldflags', I get message
`
 -std=c++amp -I/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.5/external/hcc-tot/include -std=c++amp -L/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.5/out/build/hcc/lib -Wl,--rpath=/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.5/out/build/hcc/lib -L/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.5/out/build/hcc/compiler/lib/clang/5.0.0/lib/linux -Wl,--rpath=/home/jenkins/jenkins-root/workspace/compute-rocm-rel-1.5/out/build/hcc/compiler/lib/clang/5.0.0/lib/linux -ldl -lm -lpthread -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive`

Looks like the pahts are not correct (I have no /home/jenkins...). The correct path should be '/opt/rocm/hcc-1.0/include/' and so on...
Is it bug?
I can't compile simple c++ amp

`hcc -std=c++amp -I /opt/rocm/hcc-1.0/include/ -std=c++amp -L /opt/rocm/hcc/lib/ -ldl -lm -lpthread -Wl ampTest.cpp`

```
ampTest.cpp:20:13: error: 'extent' is a private member of 'Concurrency::array_view<int, 1>'
        sum.extent,   
            ^
/opt/rocm/hcc-1.0/include/amp.h:3993:28: note: declared private here
    Concurrency::extent<N> extent;
                           ^
1 error generated.
```
(I am trying to compile code from here https://msdn.microsoft.com/en-us/library/hh265136.aspx)

**Comment by whchung** [comment]
Hi in case you use binary packages please remove "--build" when you invoke "clamp-config" or "hcc-config" and try again.

**Comment by gsedej** [comment]
Thanks for the reply. The paths seems to be correct now.
```
$ clamp-config --cxxflags --ldflags
 -std=c++amp -I/opt/rocm/hcc-1.0/include -std=c++amp -L/opt/rocm/hcc-1.0/lib -Wl,--rpath=/opt/rocm/hcc-1.0/lib -ldl -lm -lpthread -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive
```

But still error at compilation:
```
hcc `clamp-config --cxxflags --ldflags` ampTest.cpp 
ampTest.cpp:20:13: error: 'extent' is a private member of 'Concurrency::array_view<int, 1>'
        sum.extent,   
            ^
/opt/rocm/hcc-1.0/include/amp.h:3993:28: note: declared private here
    Concurrency::extent<N> extent;
                           ^
1 error generated.
```
the code is sample from here: https://msdn.microsoft.com/en-us/library/hh265136.aspx
```
#include <amp.h>  
#include <iostream>  
using namespace concurrency;  
  
const int size = 5;  
  
void CppAmpMethod() {  
    int aCPP[] = {1, 2, 3, 4, 5};  
    int bCPP[] = {6, 7, 8, 9, 10};  
    int sumCPP[size];  
  
    // Create C++ AMP objects.  
    array_view<const int, 1> a(size, aCPP);  
    array_view<const int, 1> b(size, bCPP);  
    array_view<int, 1> sum(size, sumCPP);  
    sum.discard_data();  
  
    parallel_for_each(   
        // Define the compute domain, which is the set of threads that are created.  
        sum.extent,   
        // Define the code to run on each thread on the accelerator.  
 [=](index<1> idx) restrict(amp)  
    {  
        sum[idx] = a[idx] + b[idx];  
    }  
    );  
  
    // Print the results. The expected output is "7, 9, 11, 13, 15".  
    for (int i = 0; i < size; i++) {  
        std::cout << sum[i] << "\n";  
    }  
}  
```

**Comment by whchung** [comment]
could you try use `sum.get_extent()` instead of `sum.extent`?

**Comment by scchan** [comment]
The issue is that `extent` is a private member of the `array_view` class in the C++AMP spec.

The Visual Studio implementation uses a language extension `__declspec(property(get=get_extent))` that would replace `sum.extent` with `sum.get_extent()` but this language extension is only supported by Visual Studio and not by any other compiler

https://msdn.microsoft.com/en-us/library/hh305260.aspx#array_view__extent_data_member

**Comment by gsedej** [comment]
I will close the issue, since what I taught is a bug actually wasn't.

**EDIT: I did change to `sum.get_extent()`**
The compiler crashes while compiling in following error. I might come back to c++amp later.
```$ hcc `clamp-config  --cxxflags --ldflags` ampTest.cpp ```
```
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
hcc(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x2a)[0x15a181a]
hcc(_ZN4llvm3sys17RunSignalHandlersEv+0x3e)[0x159f8be]
hcc[0x159fa0c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f46748e4390]
hcc(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x273)[0x19b02c3]
hcc(main+0x16d2)[0x9046b2]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f4673642830]
hcc(_start+0x29)[0x94ee79]
Stack dump:
0.	Program arguments: hcc -std=c++amp -I/opt/rocm/hcc-1.0/include -std=c++amp -L/opt/rocm/hcc-1.0/lib -Wl,--rpath=/opt/rocm/hcc-1.0/lib -ldl -lm -lpthread -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive ampTest.cpp 

```segmentation fault(core dumped(
