### ISSUE TITLE
--amdgpu-target= flag emits an erroneous warning

### ISSUE THREAD

**Issue by kknox** [RadeonOpenCompute/hcc#363]
When passing the `--amdgpu-target=` flag to hcc, a benign warning message is produced that confuses the user stating that the flag is not recognized.

In fact, this flag does work and the the resulting binary does contains multiple ISA's, so the warning messages below are in fact false.

```
clang-5.0: warning: argument unused during compilation: '--amdgpu-target=gfx803' [-Wunused-command-line-argument]
clang-5.0: warning: argument unused during compilation: '--amdgpu-target=gfx900' [-Wunused-command-line-argument]
```

**Comment by AlexVlx** [comment]
@kknox thank you for the report. If you don't mind my asking, how is the flag being added - e.g via target_compile_options or target_link_libraries (for a CMake based build). Thank you.

**Comment by kknox** [comment]
When I configure the project, I used -DCMAKE_CXX_FLAGS

**Comment by whchung** [comment]
`--amdgpu-target=` is a link-time option, therefore it would not be processed at compile-time.
