### ISSUE TITLE
HCC is throwing errors like "use of overloaded operator '*' is ambiguous"

### ISSUE THREAD

**Issue by sriharikarnam** [RadeonOpenCompute/hcc#386]
error log:
src/operator/svm_output.cc:40:46: error: use of overloaded operator '*' is ambiguous (with operand types 'int' and 'mshadow::half::half_t')
          dst[y][k] = margin > src[y][k] ?  2*(margin - src[y][k]) : DType(0.0f);
                                            ~^~~~~~~~~~~~~~~~~~~~~
src/operator/./svm_output-inl.h:94:7: note: in instantiation of function template specialization 'mshadow::L2_SVM<mshadow::half::half_t>' requested here
      L2_SVM(DType(param_.margin), DType(param_.regularization_coefficient), grad, label, out);

We are seeing a lot of these kind of errors while compiling with HCC, which were not reported by g++. One way we think we can fix these errors is by explicitly type-casting, but that would need us to make those changes at many places in the code.
Is there any compiler option that we can use to make HCC accept such kind of code without throwing  these kind of errors or converting the error into a warning instead?

**Comment by sriharikarnam** [comment]
[err_log.txt](https://github.com/RadeonOpenCompute/hcc/files/1151773/err_log.txt)
see err_log.txt

**Comment by aaronenyeshi** [comment]
Could you provide steps to reproduce? Also are you using latest ROCm 1.7 and latest HCC/HIP ToT.

**Comment by sriharikarnam** [comment]
@aaronenyeshi 
With latest HCC/HIP ToT and latest ROCm release this is issue is not seen.Thanks for the support.
Closing this issue
