### ISSUE TITLE
Linker error while generating executable for Thrust Library

### ISSUE THREAD

**Issue by sriharikarnam** [RadeonOpenCompute/hcc#392]
Background: Porting Thrust(Parallel Algorithms Library) to ROCm Platform

Issue: Facing linker error while generating executables in testing/backend/cuda (Attached log for reference)
[/opt/rocm/hcc-1.0/compiler/bin/clamp-device: line 134:  3771 Segmentation fault]

Steps to reproduce:
1) Download source code from https://github.com/ROCmSoftwarePlatform/Thrust/tree/Thrust_Rocm1.5_Dev (It is private repo)
2) $cd Thrust/testing/backend/cuda
3) $cp *.cu *.cpp
4) $cd Thrust/testing
5) export HIP_PLATFORM=hcc
6) /opt/rocm/hip/bin/hipcc backend/cuda/merge_by_key.cpp testframework.cpp -I../ -I. -o merge_by_key.out

Environment:

HIP version : 1.0.17174

== hipconfig
HIP_PATH : /opt/rocm/hip
HIP_PLATFORM : hcc
CPP_CONFIG : -D_HIP_PLATFORM_HCC_= -I/opt/rocm/hip/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH : /opt/rocm/hsa
HCC_HOME : /opt/rocm/hcc
HCC clang version 5.0.0 (based on HCC 1.0.17172-ac6fc20-ae1d3ca-6d828a3 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
LLVM (http://llvm.org/):
LLVM version 5.0.0svn
Optimized build.
Default target: x86_64-unknown-linux-gnu
Host CPU: pentium2

Registered Targets:
amdgcn - AMD GCN GPUs
r600 - AMD GPUs HD2XXX-HD6XXX
x86 - 32-bit X86: Pentium-Pro and above
x86-64 - 64-bit X86: EM64T and AMD64
HCC-cxxflags : -hc -std=c++amp -I/opt/rocm/hcc-1.0/includeHCC-ldflags : -hc -std=c++amp -L/opt/rocm/hcc-1.0/lib -Wl,--rpath=/opt/rocm/hcc-1.0/lib -ldl -lm -lpthread -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

[merge_by_key_linkerlog.txt](https://github.com/RadeonOpenCompute/hcc/files/1165435/merge_by_key_linkerlog.txt)

**Comment by szellmann** [comment]
I'm interested in this. I would highly appreciate a hcc backend for thrust and had actually started developing one a few months ago, but then had to stop for some reasons.

How far is the port? I had seen ROCmSoftwarePlatform/thrust but am under the impression that it uses the hip API and not hcc? Is it likely that the port will go back upstream into the thrust repo (esp. given that thrust is maintained by NV people)?

**Comment by whchung** [comment]
@sriharikarnam the reproduce step seems to be incorrect. I guess you are not able to `cp *.cu *.cpp`? do you mean to "rename each .cu file to .cpp extension"?

**Comment by sriharikarnam** [comment]
@whchung : Yes "cp *.cu *.cpp" means rename each .cu file to .cpp extension.  We have a script to do that at examples/cu_to_cpp.sh

**Comment by whchung** [comment]
@sriharikarnam with newer HCC I'm getting different linker errors other than the one described in your attached log. let me look into this and keep you posted.

**Comment by whchung** [comment]
@sriharikarnam a workaround has been published to solve the issue:
- https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/91

if you can build `hcc` from source, you can:
- apply it within `clang` directory of your `hcc` checkout.
- rebuild hcc
- rebuild hip
- rebuild your test
I've verified `merge_by_key.cpp` now builds. it doesn't run yet but you could submit another ticket afterward.

also i pushed a branch `fix_for_ctu_hcc` which contains some minor changes to let tests be easier to build, also i renamed `.cu` files to `.cpp` and put them in a separate directory. you are free to review them and see if they are worthwhile be merged into `master` branch of your work.

**Comment by whchung** [comment]
@sriharikarnam please ignore my previous comment. just now a more generic fix to this issue has been merged into `hcc` mainline:

- https://github.com/RadeonOpenCompute/hcc-clang-upgrade/pull/62

please do:

- `git pull && git submodule update` in your `hcc` checkout
- rebuild hcc
- rebuild hip
- rebuild your test

**Comment by sriharikarnam** [comment]
@whchung Thanks! Issue is fixed, we are doing regression testing. If we find anything abnormal will report in another ticket. Closing this.
