### ISSUE TITLE
Compilation error in  mxnet Library with variable arguments in kernel launch

### ISSUE THREAD

**Issue by sriharikarnam** [RadeonOpenCompute/hcc#397]
Background: Porting Mxnet Deep Learning framework to ROCm Platform

Issue: Compilaton error while passing variable arguments to kernel launch api. (see log for reference)
The variable arguments in hiplaunchkernel is throwing error as below:

 error: expected ')'
 ...Args...>), dim3(ngrid), dim3(kBaseThreadNum), 0, mshadow::Stream<gpu>::GetStream(s),N, args...);  
[errorlog.txt](https://github.com/RadeonOpenCompute/hcc/files/1638555/errorlog.txt)
  

**Environment info:**

- Operating System: Ubunut 16.04
- Compiled the code with hipcc
- ROCm Version: 1.7.60

**Steps to reproduce the issue:**

- $git clone --recursive https://github.com/ROCmSoftwarePlatform/mxnet.git
- $git clone --recursive https://github.com/ROCmSoftwarePlatform/Thrust.git
- $cd mxnet
- Remove the NVCC flag in src/operator/mxnet_op.h  at line no. 211 such as,
        #if defined( __HIP_PLATFORM_NVCC__)
    	hipLaunchKernelGGL(HIP_KERNEL_NAME(mxnet_generic_kernel<OP, Args...>), dim3(ngrid), 
        dim3(kBaseThreadNum), 0,    mshadow::Stream<gpu>::GetStream(s),N, args...); //TODO HIP .error 
        for HCC 
    	#endif         
- $export HIP_PLATFORM=hcc
- $hipcc -c -o build/src/operator/tensor/indexing_op_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3   --amdgpu-target=gfx803 --amdgpu-target=gfx900 -Xcompiler -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -I../Thrust -I.  -I. -I/opt/rocm/hipblas/include -I/opt/rocm/rocblas/include -I/opt/rocm/hiprand/include -I/opt/rocm/rocrand/include -I/opt/rocm/hcfft/include -I../mxnet/mshadow/ -I../mxnet/dmlc-core/include -fPIC -I../mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp  -I../mxnet/cub-hip -DMXNET_USE_NVRTC=0 src/operator/tensor/indexing_op.cu

Please support for fixing the variable arguments instantiation and kernel launch api

**Comment by sriharikarnam** [comment]
Updated ticket based on latest information.

**Comment by aaronenyeshi** [comment]
The command is wrong. It should be -I../Thrust, not -I../../Thrust

**Comment by aaronenyeshi** [comment]
I've created the PR https://github.com/ROCmSoftwarePlatform/mxnet/pull/3 , it should fix this issue when you use the latest HCC build from source files top of tree.

**Comment by sriharikarnam** [comment]
@aaronenyeshi 
With latest HCC/HIP ToT and latest ROCm release, the hipLaunchKernelGGL with variable arguments  issue is solved.The pull request given is solves the issue and it is merged.Thanks for the support.
Closing this issue.
