### ISSUE TITLE
hcc-config output problem.

### ISSUE THREAD

**Issue by briansp2020** [RadeonOpenCompute/hcc#41]
I installed rocm-1.0 release from repository and I'm having problem compiling hccaffe from bitbucket/multicoreware. I think the problem is that hcc-config is returning incorrect path.

> :hccaffe$ hcc-config --build --cxxflags
> -hc -std=c++amp -stdlib=libc++ -I/home/scchan/code/github/radeonopencompute/hcc.roc-1.0.20160413/hcc/include

Shouldn't the path be /opt/rocm/hcc/include ?

**Comment by scchan** [comment]
That's probably a problem in hccaffe's config.
In general, users should avoid using the --build flag because that instructs the compiler driver to include headers and link to the runtime in the compiler build environment and that's mostly used when testing the compiler.

**Comment by briansp2020** [comment]
You are right. It was my misunderstanding of the make file.
