### ISSUE TITLE
is there any way of using hcc for pre-fiji hardware?

### ISSUE THREAD

**Issue by psteinb** [RadeonOpenCompute/hcc#42]
I was wondering if HCC can be used with pre-fiji hardware (say AMD ATI FirePro S9150). if not right now, do you guys have any plans to do so?

**Comment by whchung** [comment]
Hawaii support is in the roadmap an we should be expecting it in a couple of months.

**Comment by psteinb** [comment]
ok, thanks a bunch. that gives me a clear road ahead.

**Comment by speeder** [comment]
No Tonga? If this library do what I think it does, it would be great to make simulation games (think SimCity), and Tonga + Haswell is something that many gamers own, and is not expensive, and will get even cheaper in the future...

**Comment by adityaatluri** [comment]
Hi @speeder ,
We have thought about supporting games with HSA. Here are the issues we have right now.
1. Hardware support. Right now only Fiji (GCN 1.2) based cards can use HCC. I don't know about polaris but future products can be supported. As said by Jack, Hawaii is in road map which is GCN 1.1
2. No Windows support for HSA. Note that HSA has no support on Windows. Why? HSA lets writing to the queue hardware directly which is illegal in windows driver space.
3. HCC is focused more on HPC sector. Once we get everything working fine on Fiji, we sure want to expand.

**Comment by speeder** [comment]
Still, no Tonga? Tonga is GCN 1.2 too, to the point that using any of AMDGPU-based drivers reach stellar performance in it (example: Tonga are the fastest Radeon with Dota-2+Vulkan, except in very, very high resolutions, when HBM becomes important... I doubt that Tonga hardware is faster than Fiji, so I think the drivers are just more tested on Tonga, or something like that).

**Comment by adityaatluri** [comment]
Yes. Tonga is GCN 1.2. That's why the road map shows support will be out in two months.
