### ISSUE TITLE
__cplusplus macro not changing with -std argument

### ISSUE THREAD

**Issue by PhilipDeegan** [RadeonOpenCompute/hcc#431]
Is there a different way to activate C++14 with hcc, or is it not available?

**Comment by PhilipDeegan** [comment]
It seems the addition of "-hc" or "--std=c++amp" drops __cplusplus back down to "201103"

**Comment by smithakihide** [comment]
hello, I also tried to use C++ 14 even with --std=c++14 on HCC.
but it did not work.

**Comment by PhilipDeegan** [comment]
Currently,

using ```-hc``` allows for C++14, yet ```-std=c++amp``` would override a previous call to ```-std=c++14``` so I guess this makes sense

Is ```-std=c++amp``` even necessary with ```-hc``` ?

**Comment by emankov** [comment]
> Is -std=c++amp even necessary with -hc ?

No, it is not. You need only `-std=c++14 -hc` .

**Comment by PhilipDeegan** [comment]
Seems to be the case, it's curious considering

``` /opt/rocm/bin/hcc-config --cxxflags```
outputs

```-hc -std=c++amp -I/opt/rocm/hcc/include -I/opt/rocm/include```
