### ISSUE TITLE
hcc compile failed. with error: Invalid cast (Producer: 'LLVM5.0.0svn' Reader: 'LLVM 5.0.0svn')

### ISSUE THREAD

**Issue by gonuco** [RadeonOpenCompute/hcc#453]
I have a small demo hcc program, but build failed.

following is the log: 

/opt/rocm/hcc-1.0/compiler/bin/llvm-dis: error: Invalid cast (Producer: 'LLVM5.0.0svn' Reader: 'LLVM 5.0.0svn')
/opt/rocm/hcc-1.0/compiler/bin/hc-kernel-assemble: line 90: /tmp/tmp.ikQzNJOZ9R/main-8963f3.o.ll: No such file or directory
WARNING: Linking two modules of different data layouts: '/tmp/tmp.EhDlDjAkf1/main-e0900a.kernel.bc' is '' whereas 'llvm-link' is 'e-p:64:64-p1:64:64-p2:64:64-p3:32:32-p4:32:32-p5:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-A5'

ERROR: Invalid cast (Producer: 'LLVM5.0.0svn' Reader: 'LLVM 5.0.0svn')

this log seems a typo error inside hcc which compare the llvm version with one more space diff between  producer and reader.   
could anybody confirm this is a bug?

**Comment by Prasandhmcw** [comment]
Did this get resolved ?
