### ISSUE TITLE
array_view::accelerator_pointer returns host pointer on host

### ISSUE THREAD

**Issue by syifan** [RadeonOpenCompute/hcc#458]
I am not sure if the array_view::accelerator_pointer function should return the host pointer or the device pointer if this function is called on the host. Currently, it seems that the function returns the same value as array_view::data() on the host. But from the documentation, I thought it should return the device pointer and hence, should be different from array_view::data(). I tried to pass the pointer retrieved from array_view::accelerator_pointer to the kernel and the program crashes with the error Memory Access Fault.

**Comment by bensander** [comment]
On rocm these pointer are often the same.
Using pointers to array_view is tricky - the hcc runtime usually identifies when these are used and helps with allocation and data transfer.  If you use pointer you bypass all this.
Depends on code but array might work better ?

On Sep 13, 2017, at 4:50 AM, Yifan Sun <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure if the array_view::accelerator_pointer function should return the host pointer or the device pointer if this function is called on the host. Currently, it seems that the function returns the same value as array_view::data() on the host. But from the documentation, I thought it should return the device pointer and hence, should be different from array_view::data(). I tried to pass the pointer retrieved from array_view::accelerator_pointer to the kernel and the program crashes with the error Memory Access Fault.

**Comment by syifan** [comment]
Thank you very much. Yes, Array works better in my case and I can already make Array work. 

It is good to know that the pointers are often the same and the runtime can check the kernel for the necessity of memory transfer. 

I just do not want to give up array_view, since array_view may have some advantages on APUs? What I am trying to do is to create an abstract class that wraps both array and array_view so that it can be decided at runtime. But it seems that this is not so easy.
