### ISSUE TITLE
Error: call to constructor is ambiguous for hip port of MXNet

### ISSUE THREAD

**Issue by sriharikarnam** [RadeonOpenCompute/hcc#474]
**Background**: Porting Mxnet Deep Learning framework to ROCm Platform
**Issue**:
When trying to compile device code(.cu) with hcc compiler on HIP/ROCm platform, the compiler throws error as below:

error: call to constructor of 'std::decay_t<decltype(plan)>' (aka 'mshadow::expr::Plan<mshadow::expr::ScalarExp<float>, float>') is ambiguous
    hipLaunchKernelGGL(HIP_KERNEL_NAME(MapPlanKernel<Saver, kBaseThreadBits,
[log_ambiguity_error_mxnet_hip_rocm.txt](https://github.com/RadeonOpenCompute/hcc/files/1343939/log_ambiguity_error_mxnet_hip_rocm.txt)

    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

But the same code when code compiled for HIP/CUDA platform the compiler doesn't throw any errors.
Attached details log for reference.

**Environment info:**

- Operating System: Ubunut 16.04
- Compiled the code with hipcc
- ROCm Version: 1.7.60

**Steps to reproduce the issue:**

- $git clone --recursive https://github.com/ROCmSoftwarePlatform/mxnet.git
- $git clone --recursive https://github.com/ROCmSoftwarePlatform/Thrust.git
- $cd mxnet
- $mkdir -p build/src/operator/tensor/
- Remove the NVCC flag in mshadow/mshadow/./cuda/tensor_gpu-inl.cuh at line no. 107 such as,
    		**#if defined( __HIP_PLATFORM_NVCC__)**
                hipLaunchKernelGGL(HIP_KERNEL_NAME(MapPlanKernel<Saver, kBaseThreadBits,
                   expr::Plan<DstExp, DType>,expr::Plan<E, DType> >), dim3(dimGrid), dim3(dimBlock), 0, 
                   stream, dst, xstride, dshape, plan); //Ambiguity error HCC
                **#endif**
- $export HIP_PLATFORM=hcc
- $hipcc -c -o build/src/operator/tensor/indexing_op_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 --amdgpu-target=gfx803 --amdgpu-target=gfx900 -Xcompiler -DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -I../Thrust -I. -I/opt/rocm/include -I/opt/rocm/hipblas/include -I/opt/rocm/rocblas/include -I/opt/rocm/hiprand/include -I/opt/rocm/rocrand/include  -I/opt/rocm/hcfft/include -I../mxnet/mshadow/ -I../mxnet/dmlc-core/include -fPIC -I../mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -I../mxnet/cub-hip -DMXNET_USE_NVRTC=0 src/operator/tensor/indexing_op.cu

**Comment by sriharikarnam** [comment]
Updated ticket based on latest information.

**Comment by aaronenyeshi** [comment]
Running into this issue trying to reproduce this:
```
In file included from ../mxnet/mshadow/mshadow/tensor.h:16:
../mxnet/mshadow/mshadow/./base.h:139:14: fatal error: 'cblas.h' file not found
    #include <cblas.h>
```

**Comment by sriharikarnam** [comment]
@aaronenyeshi  The above error you are facing might be because of not installing openblas. So can you please use the below command to install and recompile.
sudo apt install -y libopenblas-dev liblapack-dev

**Comment by aaronenyeshi** [comment]
I got it to install correctly.

**Comment by aaronenyeshi** [comment]
Which versions of rocRAND and blas did you install?

**Comment by sriharikarnam** [comment]
$sudo apt install -y rocm-device-libs rocm-libs rocm-opencl rocm-opencl-dev rocm-utils.
The above command installs the necessary libraries of rocm to compile.
rocblas v0.10.3.0  and rocrand v1.7.0

**Comment by aaronenyeshi** [comment]
Which branch of mxnet and thrust are you using? Seems I am getting 50+ errors.

**Comment by sriharikarnam** [comment]
@aaronenyeshi Steps to compile and reproduce are updated in summary section, having said that please attach the error log, based on that we will prepare a automated script to compile and install all the dependencies.

**Comment by aaronenyeshi** [comment]
Here is my error log attached
[mxnet_build_log.txt](https://github.com/RadeonOpenCompute/hcc/files/1668893/mxnet_build_log.txt)

**Comment by sriharikarnam** [comment]
@aaronenyeshi There is a known issue in cub-hip for which we have fixed and raised a PR.
Can you please do the change as per below PR and restart the build.
https://github.com/sriharikarnam/cub-hip/blob/a14afb86133808c94affd03a3921591b71f8435c/hip_helpers/forwarder.hpp

Update this PR in below two files
$mkdir -p build/src/operator/tensor/
$vi cub-hip/hip_helpers/forwarder.hpp
$vi ../Thrust/thrust/system/cuda/detail/cub-hip/hip_helpers/forwarder.hpp

**Comment by aaronenyeshi** [comment]
Okay, I've updated the two forwarder.hpp files with the version you linked. I have also create the directory build/src/operator/tensor/. I am still running into errors when I run your execution line.

[mxnet_build_log2.txt](https://github.com/RadeonOpenCompute/hcc/files/1674680/mxnet_build_log2.txt)

**Comment by sriharikarnam** [comment]
@aaronenyeshi .We are not able to reproduce the error in log attached above(mxnet_build_log2.txt).We are able to compile successfully with guard enabled for __HIP_PLATFORM_NVCC__. But removing the guard in file mshadow/mshadow/./cuda/tensor_gpu-inl.cuh at line number 107 will report the error as call to constructor is ambiguous. Please see the attached logs.
[guard_enabled.txt](https://github.com/RadeonOpenCompute/hcc/files/1677891/guard_enabled.txt)
[guard_removed.txt](https://github.com/RadeonOpenCompute/hcc/files/1677880/guard_removed.txt)

**My Environment info:**

Operating System: Ubunut 16.04
ROCm Version: 1.7.60

**Comment by aaronenyeshi** [comment]
I'm not too sure what is wrong. Running a `make -j16` works for me without errors.

**Comment by aaronenyeshi** [comment]
Do you need to install CUDA 8 as well?

**Comment by aaronenyeshi** [comment]
Hi @sriharikarnam , it seems that you are running on a public release of HCC. Could you update machines to use latest HCC ToT. Thank you.

**Comment by aaronenyeshi** [comment]
Hi @sriharikarnam I've been able to fix the issues. I will make a PR into mxnet repo.

**Comment by aaronenyeshi** [comment]
I've created the PR https://github.com/ROCmSoftwarePlatform/mxnet/pull/3 , it should fix this issue when you use the latest HCC build from source files top of tree.

**Comment by sriharikarnam** [comment]
@aaronenyeshi 
With latest HCC/HIP ToT and latest ROCm release this is issue is not seen.The pull request given is solves the issue and it is merged.Thanks for the support.
Closing this issue.
