### ISSUE TITLE
Is the saxpy example known to work with rocm 1.6?

### ISSUE THREAD

**Issue by tstellar** [RadeonOpenCompute/hcc#545]
The saxpy example referenced in the wiki isn't working for me with ROCM 1.6.  Is this expected to work?

**Comment by scchan** [comment]
It should work, what kind of problem you ran into?

**Comment by tstellar** [comment]
The program hangs, and I get this in dmesg:  I will verify that I have everything installed correctly.

[ 6379.897468] kfd kfd: HSA Process (PID 15461) got unhandled exception
[ 6379.897942] kfd kfd: Invalid PPR device 0:1.0 pasid 1 address 0x0 flags 0x144
[ 6379.897961] kfd kfd: Sending SIGSEGV to HSA Process with PID 15461

**Comment by tstellar** [comment]
I don't think there was an issue with my installation.  Does it work for you with 1.6 or some other version?

**Comment by scchan** [comment]
yes I'm using 1.6.  Which GPU and distro are you using?

**Comment by tstellar** [comment]
Fedora 26 I'm using a Bristol Ridge APU.

**Comment by tstellar** [comment]
I noticed some more errors in dmesg, which are probably more relevant:
[  815.678265] mem_banks_count truncated from 1 to 0
[  815.728316] Event page mmap requested illegal size
[  815.952997] Signal event wasn't created because limit was reached

**Comment by tstellar** [comment]
It looks like HSAContext::HSAContext() in mcwamp_hsa.cpp is running out of memory allocating the signal pool.

**Comment by scchan** [comment]
I don't have a Bristol Ridge right now.  
This line here sets the signal pool size
https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/lib/hsa/mcwamp_hsa.cpp#L79

Could you help me finding out what is a suitable signal pool size for this APU?  I could create a patch to make it work.  
BTW, do you know the agent name of the GPU returned by the ROCR?

**Comment by tstellar** [comment]
I've done more testing, and the problem with running out of memory was only happening on the upstream kernels, so I'll ignore this since this isn't something you support at the moment.  Using the rocm-1.6 stack with the rocm kernel.  There are no dmesg errors, but the program still hangs.  Here is some debugging output:

$ HCC_DB=4095 ./saxpy 
   hcc-init tid:1 HSAContext::HSAContext(): init HSA runtime
Message from syslogd@localhost at Nov 13 08:45:40 ...
 kernel:do_IRQ: 0.211 No irq handler for vector
   hcc-init tid:1 CPU HSA agent: AMD A12-9800E RADEON R7, 12 COMPUTE CORES 4C+8G Node ID: 0
   hcc-init tid:1 GPU HSA agent: gfx801 Node ID: 0
   hcc-init tid:1 HSADevice::HSADevice()
   hcc-init tid:1   Version Major: 1 Minor: 1
   hcc-init tid:1 found fine grained memory pool on host memory, size(MB) = 134217728
   hcc-init tid:1 using fine grained system for kernarg memory, size(MB) = 134217728
   hcc-sig tid:1  pre-allocate 512 signals
   hcc-lock tid:1  ptr:0x79f590 create lock_guard...
   hcc-queue tid:1   RocrQueue: created an HSA command queue: 0xb02000
   hcc-queue tid:1 Create new rocrQueue=0x689e30 for thief=0x79f590
   hcc-cmd tid:1   pushing 0x7abdb0 completion_signal=0  commandKind=hcCommandKernel <demangle_error>
queue#0.0 : 1 op entries
index:   0 op#1 hcCommandKernel acq=0,rel=0 completion=0x0,value=0
   hcc-lock tid:1  ptr:0x79f590 lock...
   hcc-queue tid:1 acquireLockedRocrQueue returned hwQueue=0xb02000
   hcc-aql tid:1  dispatch_aql #0.0.1(hwq=0xb02000) kernargs=76 header=b02(type=2,barrier=1,acquire=1,release=1) setup=1 grid=[512000.1.1] g
   hcc-kernarg tid:1 kernarg_address: 0x0x7f96eede6000, total of 76 bytes:
      0x000x7f96eede6000: 0xe9b6a000  0x00007f95  0x0007d000  0x00000000  
      0x000x7f96eede6010: 0x0007d000  0x00000000  0x00000000  0x00000000  
      0x000x7f96eede6020: 0x00000000  0x42c80000  0xe9974000  0x00007f95  
      0x000x7f96eede6030: 0x0007d000  0x00000000  0x0007d000  0x00000000  
      0x000x7f96eede6040: 0x00000000  0x00000000  0x00000000  
   hcc-lock tid:1  ptr:0x79f590 unlock...

**Comment by tstellar** [comment]
I ran the same program with an empty parallel_for_each and there was no hang, so maybe there is a problem with the generated ISA?

**Comment by tstellar** [comment]
After more experimentation, it looks like the hang happens when I try to read from av_x.  Reading/writing to av_y works fine.

**Comment by smithakihide** [comment]
I found ROCm dose not support Bristol ridge. this is written in ROCm's README.md.
so, you have to give up to run ROCm on Bristol ridge.

as long as I checked runtime backend of ROCm, there was no option to run the code on independent discrete GPU. ROCm seems to always need HSA compatible system. although Bristol Ridge was called as HSA compatible, but sadly, current ROCm have removed the support of Bristol Ridge already.

**Comment by tstellar** [comment]
I've hit this issue on every configuration I've tried on Fedora:
ROCm 1.6 with Bristol Ridge APU
ROCm 1.6 userspace + Upstream 4.14 kernel with Bristol Ridge APU
ROCm 1.6 userspace with Vega10 GPU / Ryzen CPU

I wonder if this is an issue specific to the Fedora kernel.  Do you know if this was validated on Fedora?

I will try Ubuntu on these systems and see if that works.

**Comment by tstellar** [comment]
I just was able to get this working on Fedora with my Vega10 GPU/ Ryzen CPU system, so I'm going to close this issue

**Comment by ghostplant** [comment]
@scchan Hi, I am using rocm-2.0.0 installed on my APU to run **very-heavy** OpenCL program and I also got errors from kfd like:
```sh
[194478.209843] kfd kfd: Invalid PPR device 0:0.0 pasid 32768 address 0x7FC500A15000 flags 0x144
[194478.209851] kfd kfd: Invalid PPR device 0:0.0 pasid 32768 address 0x7FC500A15000 flags 0x144
[194478.209859] kfd kfd: Invalid PPR device 0:0.0 pasid 32768 address 0x7FC500A14000 flags 0x144
[196222.608740] Signal event wasn't created because limit was reached
```
What should be done to increase the limit? Would it still work by changing the value of queue size below?
https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/lib/hsa/mcwamp_hsa.cpp#L79

According to latest ROCm codes, I saw multiple related size are defined, so which one should be get changed to fix `Signal .. limit was reached`?
