### ISSUE TITLE
How can I type ”`” ?　

### ISSUE THREAD

**Issue by smithakihide** [RadeonOpenCompute/hcc#554]
How can I type ”```” ?　
this is needed for the below command.
``hcc `clamp-config --cxxflags --ldflags` foo.cpp``
sorry for such this stupid question.
but, actually I am in trouble.

**Comment by aaronenyeshi** [comment]
HI, that key is the “accent grave” key on the same key as the tilde key on the top left of the keyboard. Usually it is beside “1” key

**Comment by smithakihide** [comment]
thank you. I could find.
I could type this by Shift + @
