### ISSUE TITLE
Why there are two instructions to compile HCC,  HCC and HCC wiki?

### ISSUE THREAD

**Issue by smithakihide** [RadeonOpenCompute/hcc#555]
hello. thank you for reading.

I wonder why there are two instructions to compile HCC.
I found [https://github.com/RadeonOpenCompute/hcc](url) (will denoted as hcc in this text)and [https://github.com/RadeonOpenCompute/hcc/wiki](url) (will denoted as hcc/wiki in this text)

here is build command in "hcc"
`cmake -DCMAKE_BUILD_TYPE=Release ..`

and this is the "hcc/wiki" one.
`cmake ../hcc`

and although there is the information about dependent library to compile hcc in "hcc/wiki", but there is no it in "hcc".

I think these two instructions should be merged.

**Comment by scchan** [comment]
The reason is it depends on where your build directory is relative to the hcc source directory

**Comment by smithakihide** [comment]
although your answer was a little different from what I wanted to ask, thank you to reply.
