### ISSUE TITLE
Regression after migrating to ROCm version 1.6.180 from 1.6.148

### ISSUE THREAD

**Issue by sriharikarnam** [RadeonOpenCompute/hcc#556]
The below linker error is being faced while generating executables in Thrust Library after migration to ROCm 1.6.180 . The generation of executables was successful on previous ROCm version 1.6.148.

**Error**:  error: can't create dynamic relocation R_AMDGPU_REL32_HI against symbol: thrust::detail::cons<thrust::system::cuda::detail::bulk_::detail::cursor<0u>, thrust::detail::cons<thrust::zip_iterator<thrust::tuple<int*, int*, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type> >,thrust::detail::cons<thrust::detail::wrapped_function<thrust::detail::unary_transform_functor<thrust::identity<int> >, void>, thrust::detail::cons<long, thrust::null_type> > > >::~cons() in readonly segment; recompile object files with -fPIC

**Current Working Setup:**
Package: rocm
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 13
Maintainer: Advanced Micro Devices Inc.
Architecture: amd64
Version: 1.6.180
Depends: rocm-dev, compute-firmware, linux-headers-4.11.0-kfd-compute-rocm-rel-1.6-180, linux-image-4.11.0-kfd-compute-rocm-rel-1.6-180
Description: Radeon Open Compute (ROCm) Runtime software stack
Homepage: https://github.com/RadeonOpenCompute/ROCm

Steps to reproduce the above error:

**Step 1:** Clone thrust repository from https://github.com/ROCmSoftwarePlatform/Thrust.git

**Step 2:** Replace thrust/system/cuda/detail/cub with cub directory present in https://github.com/ROCmSoftwarePlatform/cub-hip/tree/hip_port_1.7.3. Replace cub according to the directory structure mentioned in README.md

**Step 3:** Navigate to examples folder.
$ cd examples
$ cp sum.cu sum.cpp
$ export HIP_PLATFORM=hcc
$ hipcc -I../ sum.cpp -o sum.out

**Comment by mangupta** [comment]
@sriharikarnam could you try adding -fPIC to the hipcc options when building the thrust library and see if it helps?

**Comment by sriharikarnam** [comment]
Hi Maneesh
We tried adding -fPIC option to hipcc earlier, but the issue was not resolved.
Please find attached log for reference.
[sum_error_log.txt](https://github.com/RadeonOpenCompute/hcc/files/1491412/sum_error_log.txt)

**Comment by sriharikarnam** [comment]
We are facing the above mentioned linker issue in the classes where there is no user defined destructor.

We tried the below workaround for this error:
Defined destructor for the class pointed in the linker error. This resolved error for that particular class but again reappears for other classes recursively. 
In general the compiler should define a default destructor if there is no user-defined destructor.

**Comment by scchan** [comment]
Could you try with the roc-1.7.x branch of hcc?  It works for me and it will be released very soon.

Follow the steps described in the wiki: https://github.com/RadeonOpenCompute/hcc/wiki#building-hcc-from-source

Except that after cloning the hcc source tree, then do 

`git checkout origin/roc-1.7.x; git submodule update`

and then continue to configure the hcc build with `cmake`

**Comment by sriharikarnam** [comment]
@scchan  Thanks for your inputs,
We have upgraded hcc to the latest version(HCC 1.1.17462-5b2aa08-42ceed8-4c229d3) by following the above mentioned steps.
The issue is now resolved.
