### ISSUE TITLE
"HCC_RUNTIME" about backend option

### ISSUE THREAD

**Issue by smithakihide** [RadeonOpenCompute/hcc#565]
in the past HCC implementation, there are some option to specify which environment to run the code compiled with HCC.

I want OpenCL Back end.
is there still such this option?
or please implement CPU back end mode.

but if there is no plan to implement either OpenCL or CPU mode, I think this option should be removed. it still work and I got strange result. this will be confusing.

**Comment by whchung** [comment]
@scchan @bensander do we want to consider deprecating x86 backend in HCC? It has been stale for quite awhile and no real-world applications depend on it.

**Comment by smithakihide** [comment]
thank you to answer.
there are 3 things what I 'd like to say in addition.

1,
yes, eventually we would not need CPU back end as you said.
but there would be experimental case before large scale calculation. such experimental case will consist of small data not to be able to extract enough advantages of GPU.  so we need CPU back end at the development time.

2, 
As I said, if you don't have plan to support CPU back end, `export HCC_RUNTIME=CPU` option which still work even in current newest HCC should be removed.

3,
We have to demonstrate how fast HCC is compared with CPU only system.
to make this comparison, we need CPU back ended performance on the completely same code as HCC version. there are still many people to continue using CPU multicore platform. if there is no CPU back end in HCC, we have to create the another code with STL libraries to show the advantage of GPU. if there was CPU backend in HCC and it worked as fast as STL libraries,  we can prove HCC is good easily.
