### ISSUE TITLE
Having trouble compiling, finding libunwind.h

### ISSUE THREAD

**Issue by alexanderkjeldaas** [RadeonOpenCompute/hcc#580]
On NixOS, all of the dependencies are in separate locations, and I have problems figuring out which option I can modify to get libunwind.h available.

At the end of the compile I get:

```
[ 92%] Building OCL object rocdl/opencl/CMakeFiles/opencl_lib.dir/src/media/umin3.cl
cd /tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/build/rocdl/opencl && /tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/build/compiler/./bin/clang -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/build/include -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/include -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/compiler/include -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/rocdl/opencl/src/integer -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/rocdl/opencl/src/workgroup -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/rocdl/opencl/../irif/inc -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/rocdl/opencl/../ocml/inc -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/rocdl/opencl/../ockl/inc -I/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/rocdl/opencl/../oclc/inc  -o CMakeFiles/opencl_lib.dir/src/media/umin3.cl -Werror -x cl -Xclang -cl-std=CL2.0 -fblocks -target amdgcn--amdhsa-amdgizcl -DCL_VERSION_2_0=200 -D__OPENCL_C_VERSION__=200 -Dcl_khr_fp64 -Dcl_khr_fp16 -Dcl_khr_subgroups -Dcl_khr_int64_base_atomics -Dcl_khr_int64_extended_atomics -Xclang -finclude-default-header  -emit-llvm -c /tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/rocdl/opencl/src/media/umin3.cl
In file included from /tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/lib/mcwamp.cpp:8:
/tmp/nix-build-hcc-2017-12-06.drv-8/hcc-5ce213a/build/include/hc_rt_debug.h:6:10: fatal error: 'libunwind.h' file not found
#include <libunwind.h>
```

I'm using `-DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DHSA_HEADER_DIR=${rocr-runtime}/include -DHSA_LIBRARY_DIR=${rocr-runtime}/lib`

I'm also setting

```
CMAKE_CXX_FLAGS="-I${roct}/include -I${libunwind.dev}/include";
```

How can I influence the include paths at this point in the compilation?

**Comment by scchan** [comment]
could you try inserting the cmake command `target_include_directories` here https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/scripts/cmake/MCWAMP.cmake#L56

**Comment by pfultz2** [comment]
You should set `CMAKE_PREFIX_PATH` to where all the dependencies are. This is set to the installation paths of the dependencies. That is, if you install libunwind into `$UNWIND_PATH` and install rocr into `$ROCR_PATH`, then you should set `CMAKE_PREFIX_PATH` with something like `-DCMAKE_PREFIX_PATH=$ROCR_PATH;$UNWIND_PATH`(and there is no need to use the advance `HSA_*` cmake variables either).
