### ISSUE TITLE
error: invalid argument '-std=c++amp' not allowed with 'C/ObjC'

### ISSUE THREAD

**Issue by sunyifan112358** [RadeonOpenCompute/hcc#59]
I was compiling some code that was mostly written in plain c++ and a function is written with C++ HC. When compile, I got the error in the title. Even if I only use `hcc-config --cxxflags` to compile a .o file, it will still give me this error. Is there any explaination to this error? Can that be caused by may header file has the extension of h rather than hpp? I think .h is still very wildly used for c++ headers, so why forbidding .h headers?

**Comment by whchung** [comment]
@sunyifan112358 hcc does support .h header files. You should be able to find quite a few under include directory. If possible could you come up with a minimal case and post on gist, so I can understand your issue better?
