### ISSUE TITLE
Undefined LIBCXX_HEADER during compilation of hcc

### ISSUE THREAD

**Issue by osamaGkhafagy** [RadeonOpenCompute/hcc#633]
I'm building the **hiptf** platform from source using the provided documentation. I'm using _debian 8, AMD Radion 8670m gpu_. I got stuck at this instruction **`cd ~ && mkdir -p build.hcc && cd build.hcc && cmake -DCMAKE_BUILD_TYPE=Release ../hcc`** at which the compilation is terminated with the following error:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/lonewolf/hcc/amp-conformance/LIBCXX_HEADER
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
/home/lonewolf/hcc/lib/LIBCXX_HEADER
   used as include directory in directory /home/lonewolf/hcc/lib
   used as include directory in directory /home/lonewolf/hcc/lib
/home/lonewolf/hcc/lib/cpu/LIBCXX_HEADER
   used as include directory in directory /home/lonewolf/hcc/lib/cpu
   used as include directory in directory /home/lonewolf/hcc/lib/cpu
/home/lonewolf/hcc/lib/hsa/LIBCXX_HEADER
   used as include directory in directory /home/lonewolf/hcc/lib/hsa
   used as include directory in directory /home/lonewolf/hcc/lib/hsa
   used as include directory in directory /home/lonewolf/hcc/lib/hsa
   used as include directory in directory /home/lonewolf/hcc/lib/hsa
/home/lonewolf/hcc/utils/gtest/LIBCXX_HEADER
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
LIBCXX_HEADER
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/utils/gtest
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance
   used as include directory in directory /home/lonewolf/hcc/amp-conformance

**Comment by whchung** [comment]
@osamaGkhafagy your distro and GPU is not currently supported. please help follow steps at: https://github.com/RadeonOpenCompute/ROCm to make sure you have a proper ROCm stack installed. Once installed you don't need to build `hcc` from source.
