### ISSUE TITLE
HCC compile permission error requiring recompile

### ISSUE THREAD

**Issue by zgu153522** [RadeonOpenCompute/hcc#65]
Typically hcc seems to need to compile something twice - first time it gives a permission denied error, and the second time it goes through.
```
hcc `hcc-config --cxxflags --ldflags` proto3.cpp -o proto3.o
/opt/rocm/hcc-lc/compiler/bin/llvm-link: /tmp/tmp.BTueUbkHwn/proto3.kernel.bc:1:1: error: expected top-level entity
ELF@▒@▒#@8@
/opt/rocm/hcc-lc/compiler/bin/llvm-link: error loading file '/tmp/tmp.BTueUbkHwn/proto3.kernel.bc'
ld: cannot open output file /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: Permission denied
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by whchung** [comment]
@zgu153522 From the error message it seems to be a bug in the backend ("-lc" part in "hcc-lc").Would it be possible to let me know your configuration (ROCm stack version , hcc --version), plus perhaps a minimized case to reproduce the issue so I could forward to backend team for further investigation?

**Comment by whchung** [comment]
Also, could you try build the program with hcc-hsail ? You could do that by:
```
export HCC_HOME=/opt/rocm/hcc-hsail

**Comment by zgu153522** [comment]
I have:
```
HCC clang version 3.5.0  (based on HCC 0.10.16185-d649442-7461349 LLVM 3.5.0svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```
Any test case seems to work - I made one that launches an empty kernel.  But I think the pattern is:
if the output file already exists (from a previous call to compile), hcc will put out that error and remove the executable.  Then a subsequent call will work since the file isn't there.  I can confirm that manual removal like this will work:
```
rm hcctest.o
hcc `hcc-config --cxxflags --ldflags` hcctest.cpp -o hcctest.o
```
It may just be that I'm using it wrong and need to remember to sort of 'make clean' it before recompiling.  If so let's close the ticket.
