### ISSUE TITLE
Cannot run the saxpy example - HSA_STATUS_ERROR (0x1000)

### ISSUE THREAD

**Issue by JGO95** [RadeonOpenCompute/hcc#652]
I installed the latest ROCm version (1.7) that comes with HCC. However, when I was trying to run some of the HIP samples, all of them would crash.

Since the error code mentioned hcc, I downloaded and compiled the saxpy sample mentioned in the documentation of hcc with the following input:

> hcc \`hcc-config --cxxflags --ldflags\` --amdgpu-target=gfx701 saxpy.cpp -o saxpy

but the program still crashes with the error code below. I also tried to target the Kaveri GPU 
( --amdgpu-target=gfx700), but I get the same error when running.

`Backtrace:`
`0x00007ffbaa5d90b7:	Kalmar::HSAContext::HSAContext() + 0xa27`
`0x00007ffbaa5d6f46:	_GLOBAL__sub_I_mcwamp_hsa.cpp + 0x5f6`
`0x00007ffbad49b6ba:	_dl_rtld_di_serinfo + 0x706a`
`0x00007ffbad49b7cb:	_dl_rtld_di_serinfo + 0x717b`
`0x00007ffbad4a08e2:	_dl_find_dso_for_object + 0xcf2`
`0x00007ffbad49b564:	_dl_rtld_di_serinfo + 0x6f14`
`0x00007ffbad49fda9:	_dl_find_dso_for_object + 0x1b9`
`0x00007ffbad283f09:	<unknown function> + 0x1b9`
`0x00007ffbad49b564:	_dl_rtld_di_serinfo + 0x6f14`
`0x00007ffbad284571:	dlerror + 0x2c1`
`0x00007ffbad283fa1:	dlopen + 0x31`
`0x0000000000405431:	Kalmar::CLAMP::GetOrInitRuntime() + 0x261`
`0x000000000040637b:	Kalmar::KalmarBootstrap::KalmarBootstrap() + 0x8b`
`0x00000000004062c9:	__hcc_shared_library_init + 0x29`
`0x000000000041568d:	__libc_csu_init + 0x4d`
`0x00007ffbabf737bf:	__libc_start_main + 0x7f`
`0x0000000000407479:	_start + 0x29`

`### HCC STATUS_CHECK Error: HSA_STATUS_ERROR (0x1000) at file:mcwamp_hsa.cpp line:3409`
`Aborted (core dumped)`

I'm currently running the following hardware:
•APU: AMD A10-7850K APU
•AMD Radeon R9 290X - Hawaii XT
•OS: Ubuntu 16.04.4 LTS (Linux 4.11.12-041112-generic)

I don't intend to use the integrated Kaveri GPU for development, I just want to run code in the dGPU.

Can someone tell me if they managed to get a setup like this running? I've read that current version of ROCm does not officially support Kaveri CPUs (or that support was dropped at some point, not quite clear). If that is correct, can someone point me to a version that would run on my hardware (if it exists)?

**Comment by whchung** [comment]
@JGO95 please build and check if `vector_copy` sample under `/opt/rocm/hsa/sample` works. Unfortunately, based on your configuration I don't think it's possible to execute ROCm properly. To my understanding no version of ROCm exists which allows you dispatch GPU kernels to a dGPU from an Kaveri APU.

**Comment by JGO95** [comment]
Thank you for your answer. I tried to build and run the vector_copy sample as suggested and got this message:

`Initializing the hsa runtime succeeded.`
`Checking finalizer 1.0 extension support succeeded.`
`Generating function table for finalizer succeeded.`
`Getting a gpu agent failed.`

Even if I can't dispatch GPU kernels to a dGPU from a Kaveri APU, shouldn't I be able to run the saxpy code in the Kaveri GPU building with --amdgpu-target=gfx700? 

Just one more question: so in your experience, if I just upgrade the CPU to a newer one, should this setup work?

**Comment by aditya4d** [comment]
ROCm does not work on machines released before Ryzen. The reason is, ROCm requires PCIe atomics which is not present in PCIe Gen 2 (Pre-Ryzen AMD processors are all PCIe Gen 2).

**Comment by whchung** [comment]
@JGO95 please refer to https://github.com/RadeonOpenCompute/ROCm#supported-cpus for supported CPUs.
