### ISSUE TITLE
"Error : No device code available for function" on ROCm 1.7.137(Beta 4) for MXNet HIP Port

### ISSUE THREAD

**Issue by sriharikarnam** [RadeonOpenCompute/hcc#662]
**Background:** Porting Mxnet Deep Learning framework to ROCm Platform 

**Issue :** No device code available for function 

**Error:** 
terminate called after throwing an instance of 'std::runtime_error'
  what():  No device code available for function: _ZN7mshadow4cuda13MapPlanKernelINS_2sv6savetoELi8ENS_4expr4PlanINS_6TensorINS_3gpuELi1EfEEfEENS5_INS4_9ScalarExpIfEEfEEEEvT1_jNS_5ShapeILi2EEET2_
Aborted (core dumped)

While launching kernel using hipLaunchKernelGGL we are facing above mentioned error on ROCm Version: 1.7.137. 
Could you please help us to debug the issue. 	

Please find the attached log. 
[mxnet_log.txt](https://github.com/RadeonOpenCompute/hcc/files/1875939/mxnet_log.txt)

Also attached LLVM and ISA dump for the issue.
[LLVM and ISA dumps.zip](https://github.com/RadeonOpenCompute/hcc/files/1828779/LLVM.and.ISA.dumps.zip)

**Environment info:**

- Operating System: Ubunut 16.04

- ROCm version:
$  dpkg -s rocm-dkms
Package: rocm-dkms
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 13
Maintainer: Advanced Micro Devices Inc.
Architecture: amd64
Version: 1.7.137
Depends: rocm-dev, compute-firmware, rock-dkms
Description: Radeon Open Compute (ROCm) Runtime software stack
Homepage: https://github.com/RadeonOpenCompute/ROCm

- HIP environment details:
$ hipconfig --full
 HIP version  : 1.5.18073
 == hipconfig
 HIP_PATH     : /opt/rocm
 HIP_PLATFORM : hcc
 CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/include -I/opt/rocm/hcc/include
 == hcc
 HSA_PATH     : /opt/rocm/hsa
 HCC_HOME     : /opt/rocm/hcc
 HCC clang version 6.0.0 (ssh://gerritgit/compute/ec/hcc-tot/clang 
 ac8732c272d3ce6a4d1ee6aa636f06d44cd5170c) (ssh://gerritgit/compute/ec/hcc-tot/llvm 
 710f135c41925e12aa088c26e1a9f583b1778fbe) (based on HCC 1.2.18063-7e18c64-ac8732c-710f135 
 )
 Target: x86_64-unknown-linux-gnu
 Thread model: posix
 InstalledDir: /opt/rocm/hcc/bin
 Can't exec "/opt/rocm/hcc/compiler/bin/llc": No such file or directory at /opt/rocm/bin/hipconfig line 132.
 HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/include -I/opt/rocm/includeHCC-ldflags  :  -hc -
 std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lunwind -lhc_am -Wl,--
 whole-archive -lmcwamp -Wl,--no-whole-archive

**Steps to reproduce the issue:**

- $ git clone --recursive https://github.com/ROCmSoftwarePlatform/Thrust
- $ git clone --recursive https://github.com/ROCmSoftwarePlatform/mxnet
- $ cd mxnet
- #Add thrust path to the Makefile
- $ export HIP_PLATFORM=hcc
- $ make -jn (n = no of cores)
- $ cd python
- $ sudo python setup.py install
- $ cd ../mxnet/example/bayesian-methods/
- $ export HIP_TRACE_API=1
- $ export HCC_DB=7
- $ python bdk_demo.py

**Comment by whchung** [comment]
@scchan / @aaronenyeshi wondering if you could lend a hand here

**Comment by NEELMCW** [comment]
Same issue we experience  with hipCNTK as well

**Comment by scchan** [comment]
@NEELMCW you encountered the same error in hipCNTK because it launches the same kernel?

**Comment by NEELMCW** [comment]
Nope its on a different set of kernel. CNTK today supports float, double and half types. When we attempted to build with all datatypes on ROCM we hit upon this issue. Currently we have disabled half and proceeded further to evaluate for float and double.

**Comment by sriharikarnam** [comment]
@scchan
HCC team suspects this issue to be because of "Symbol Multiply defined!" errors(C++ ODR) which were getting ignored by HCC linker script and subsequently kernel code not being generated in libmxnet.so.
We have fixed those errors in MXNet and cub-hip but we encounter below errors. 
[Detailed log(log.txt.zip) is attached]

note: !srcloc = 18284130
<inline asm>:1:2: error: unknown directive
        .reg .s32 r0;.reg .pred p;shfl.up.b32 r0
        ^
note: !srcloc = 18284130
<inline asm>:1:2: error: unknown directive
        .reg .s32 r0;.reg .pred p;shfl.up.b32 r0
        ^
note: !srcloc = 18284130
<inline asm>:1:2: error: unknown directive
        .reg .s32 r0;.reg .pred p;shfl.up.b32 r0
        ^
note: !srcloc = 18284130
Generating AMD GCN kernel failed in llc for target: gfx900
Generating AMD GCN kernel failed in llc for target: gfx900
Generating AMD GCN kernel failed in llc for target: gfx803
clang-6.0: error: linker command failed with exit code 3 (use -v to see invocation)
Died at /opt/rocm/bin/hipcc line 498.

[log.txt.zip](https://github.com/RadeonOpenCompute/hcc/files/1894697/log.txt.zip)

**Comment by scchan** [comment]
@sriharikarnam 
The error is caused by code containing inline asm statements with PTX instructions (e.g. shfl.up) because AMD GPUs don't support them.  You probably have to replace them with the __shfl builtin implemented in HIP.

**Comment by sriharikarnam** [comment]
@scchan 
Thanks for your inputs. We are able to launch device kernels and successfully validate some of the MXNet training tests. We will continue testing all the available MXNet tests to check for any corner case issues.
**Issue:** HCC's linker script did not catch the "symbol multiply defined!" errors, leading to no GPU kernels in compiled libmxnet.so
**Resolution:**  Fixed C++ ODR and other porting issues in CUB-HIP to generate clean libmxnet.so
(We will provide PR for the changes made in CUB-HIP)
We will finish the entire testing and close this ticket if there are no further issues

**Comment by sriharikarnam** [comment]
This issue is fixed and able to exercise device kernels on ROCm 1.7 Beta4 codebase. we have checked-in changes to CUB-HIP branch (https://github.com/ROCmSoftwarePlatform/cub-hip/tree/cubhip_mxnet)
