### ISSUE TITLE
ROCm agent detector failed to execute correctly...

### ISSUE THREAD

**Issue by justxi** [RadeonOpenCompute/hcc#663]
Hello,

when I compile the example saxpy, I get:
clang-7.0: warning: ROCm agent detector failed to execute correctly; using default -amdgpu-target instead [-Wfallback]
objdump: /usr/lib64/libm.a: File format not recognized
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)
'auto' is not a recognized processor for this target (ignoring processor)

with "-amdgpu-target=gfx803" for the Radeon Rx 560 it works.
I compiled "hcc" from source. 
Is the "ROCm agent detector" an additional package?

**Comment by whchung** [comment]
@justxi the tool is installed under `/opt/rocm/bin/rocm_agent_enumerator`. It's a python script which calls and parses output from another program `/opt/rocm/bin/rocminfo`. RX560 is not generally a target we consider for GPGPU computing so we could have some issue here.

Could you help run these two programs and share the outputs?

You can also check the source codes of those programs at:
https://github.com/RadeonOpenCompute/rocminfo

**Comment by justxi** [comment]
Thanks thats it. I build "HCC" from source for Gentoo Linux, so I was missing "rocminfo" and "rocm_agent_enumerator". Now the error is gone.

**Comment by justxi** [comment]
Output of "rocminfo":
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (number of timestamp)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 1800X Eight-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0                                  
  Queue Min Size:          0                                  
  Queue Max Size:          0                                  
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768KB                            
  Chip ID:                 0                                  
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):3600                               
  BDFID:                   0                                  
  Compute Unit:            16                                 
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    16444504KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16444504KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx803                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128                                
  Queue Min Size:          4096                               
  Queue Max Size:          131072                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16KB                               
  Chip ID:                 26607                              
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):1176                               
  BDFID:                   8960                               
  Compute Unit:            14                                 
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64                                 
  Workgroup Max Size:      1024                               
  Workgroup Max Size Per Dimension:
    Dim[0]:                  67109888                           
    Dim[1]:                  587203584                          
    Dim[2]:                  0                                  
  Grid Max Size:           4294967295                         
  Waves Per CU:            40                                 
  Max Work-item Per CU:    2560                               
  Grid Max Size per Dimension:
    Dim[0]:                  4294967295                         
    Dim[1]:                  4294967295                         
    Dim[2]:                  4294967295                         
  Max number Of fbarriers Per Workgroup:32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4194304KB                          
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64KB                               
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    AMD:AMDGPU:8:0:3                   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Dimension: 
        Dim[0]:                  67109888                           
        Dim[1]:                  1024                               
        Dim[2]:                  16777217                           
      Workgroup Max Size:      1024                               
      Grid Max Dimension:      
        x                        4294967295                         
        y                        4294967295                         
        z                        4294967295                         
      Grid Max Size:           4294967295                         
      FBarrier Max Size:       32                                 
*** Done ***             

Output of "rocm_agent_enumerator":
gfx000
gfx803

**Comment by justxi** [comment]
The "rocm_agent_enumerator" is only running with Python 2.
With Python 3, there are two errors with "print" and after adding "( )" to fix this,  the output is only "gfx000".

You said that "RX560" it not a general target... What are the general targets?

While compiling "saxpy" there is the following output:
 objdump: /usr/lib64/libm.a: File format not recognized

Is "libm.a" needed?

What is the difference between "hcc" and "HCC-Native-GCN-ISA"?

**Comment by whchung** [comment]
@justxi since you are building everything from source on an unsupported distro, Gentoo, all bets are off. I'll need your help to tune the tools to make them behave properly on Gentoo.

The expected output from `rocm_agent_enumerator` is:

```
gfx000
<list of supported GCN ISA version found on the system>
```

So the output you got running `rocm_agent_enumerator` on Python2 is correct. Please help submit a PR to fix it for Python 3 and either me @whchung or @jedwards-AMD could review it.

For GFX8 products, RX580, Fiji Nano are tested more often. For GFX9, Vega FE/56/64, MI25 are validated. But now since `rocm_agent_enumerator` sees your RX560 and report it as `gfx803` we are past that point now.

`-lm` is specified at: https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/hcc_config/hcc_config.cpp#L159

and it's needed. Again I'll need your help understanding the behavior on Gentoo.

`objdump` is used in various places at link time. For example:
https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/lib/clamp-link.in#L388

`HCC-Native-GCN-ISA` is deprecated. I will take it down. Please only use `hcc`.

**Comment by justxi** [comment]
@whchung I will do what I can, to get it working on Gentoo. I uploaded my current results to https://bugs.gentoo.org/650804.

I bought a RX560 to test the ROC stuff (used on FX 8350 before) and added a Ryzen 7 because of PCIe Atomics... RX Vega is currently out of my scope... So nice to see that the effort is not for nothing.

Regarding rocminfo I will create an PR.
