### ISSUE TITLE
Building HCC from source files

### ISSUE THREAD

**Issue by justxi** [RadeonOpenCompute/hcc#665]
Hi,

there is a HCC 1.7.0 file release. For "llvm", "lld" and "ROCm-Device-Libs" there are also file releases for version 1.7.0. 

For "hcc-clang-upgrade" and  "compiler-rt" the latest version number is 1.6.0. And for "clang-tools-extra" there is no numbered file release. 

So which files should be used from "hcc-cland-upgrade", "compiler-rt" and "clang-tools-extra" to build HCC 1.7.0 based on file releases?

Thanks for any hints.

**Comment by whchung** [comment]
We use git submodules ( https://git-scm.com/docs/git-submodule ). Just check out `hcc` with `recursive` get you all required submodules.

```
# get tip
git clone --recursive -b clang_tot_upgrade https://github.com/RadeonOpenCompute/hcc.git

# get ROCm 1.7.x release branch
git clone --recursive -b roc-1.7.x https://github.com/RadeonOpenCompute/hcc.git
```
