### ISSUE TITLE
Issue generating kernel

### ISSUE THREAD

**Issue by Jorghi12** [RadeonOpenCompute/hcc#704]
LLVM ERROR: Cannot select: 0x43df9d8: v2i16 = SMAX3 0x4468f20, 0x44ec5d0, 0x448d4c8
  0x4468f20: v2i16 = SMAX3 0x44841d0, 0x43dfb10, 0x45fe528
    0x44841d0: v2i16 = SMAX3 0x4463470, 0x4467a60, 0x4465700
      0x4463470: v2i16 = smax 0x447ee40, 0x428cbf0
        0x447ee40: v2i16,ch = CopyFromReg 0x42bdc40, Register:v2i16 %57
          0x4471360: v2i16 = Register %57
        0x428cbf0: v2i16,ch = CopyFromReg 0x42bdc40, Register:v2i16 %58
          0x43df080: v2i16 = Register %58
      0x4467a60: v2i16,ch = CopyFromReg 0x42bdc40, Register:v2i16 %59
        0x428cd28: v2i16 = Register %59
      0x4465700: v2i16,ch = CopyFromReg 0x42bdc40, Register:v2i16 %60
        0x4468d80: v2i16 = Register %60
    0x43dfb10: v2i16,ch = CopyFromReg 0x42bdc40, Register:v2i16 %61
      0x4465150: v2i16 = Register %61
    0x45fe528: v2i16,ch = CopyFromReg 0x42bdc40, Register:v2i16 %62
      0x44ec770: v2i16 = Register %62
  0x44ec5d0: v2i16,ch = CopyFromReg 0x42bdc40, Register:v2i16 %63
    0x446c9e0: v2i16 = Register %63
  0x448d4c8: v2i16,ch = CopyFromReg 0x42bdc40, Register:v2i16 %64
    0x44718a8: v2i16 = Register %64
In function: _Z15kernelReduceAllIN6thrust8identityIsEE9ReduceMaxIsES4_ssjLi1EEv10TensorInfoIT2_T4_ES7_T3_T_T0_T1_PS9_
Generating AMD GCN kernel failed in llc for target: gfx900

**Comment by whchung** [comment]
@Jorghi12 please help provide steps to reproduce, or supply a reduced test case.

**Comment by Jorghi12** [comment]
https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCNumerics.cuh#L82
https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCTensorMathReduce.cuh#L114
https://github.com/pytorch/pytorch/blob/master/aten/src/THC/THCReduceAll.cuh#L40

This is the instruction that's being ran leading to the SMAX3 usage.
"a > b ? a : b"

**Comment by whchung** [comment]
@Jorghi12 folks working on `hcc` project may not know how to build your project. To help easily reproduce the issue you are seeing please help provide fool-proof steps to build your application.

Also from the log it could be an issue in the compiler backend, if you could provide LLVM IR dump with env var `KMDUMPLLVM=1` when you *link* the program that could be very helpful.

**Comment by scchan** [comment]
@Jorghi12 We don't have instructions to reproduce this problem, please re-open if the problem still exists with the latest hcc and provide a test.
