### ISSUE TITLE
LDS barrier synchronization problem

### ISSUE THREAD

**Issue by zgu153522** [RadeonOpenCompute/hcc#705]
I discovered that for some reason it seems like wait_with_tile_static_memory_fence doesn't seem to apply to the whole tile.  I'm attaching the smallest kernel that I can reproduce the issue in.  I have a Radeon Instinct MI25 on an Epyc 7551P.  This kernel initializes some LDS memory to 0, then barrier, then sets the LDS memory to -1 *using a different ordering of work-items*, then barrier, and then writes back to global memory.  I noticed that if I used the same work-items to write -1 as I used for initializing to 0, then it works properly, but this does not follow how tile barriers are supposed to work.

The test harness program will output the number of QWORDS that came out to be 0 instead of -1 (e.g. the initialization of LDS to 0 somehow happened after the later instruction across the barrier to set it to -1).

[ldsbug.zip](https://github.com/RadeonOpenCompute/hcc/files/1968362/ldsbug.zip)

Edit: I see this problem also on my R9 Nano.

**Comment by zgu153522** [comment]
Just wanted to make sure somebody is looking at this?  I'm not really sure if it is a problem with HCC or something lower level.

**Comment by scchan** [comment]
I was able to reproduce the problem with a simpler test case.  It looks like the load from tile_static gets the wrong value for some reason.  There isn't anything that really stands out in the ISA so I'm still investigating.

**Comment by smartbitcoin** [comment]
@zgu153522    in your ldsbug.cpp,   if you use tile size =1024 instead of 1000,   you won't see this issue.
gcn use SIMD is 16 lane,  tile size should be 16x

**Comment by scchan** [comment]
I've simplified this test case such that each workitem write and read from their own slot of lds memory (therefore no barrier is needed)  and this bug is still observable.  Changing to 1024 makes it work but 1000 is a valid size so it should work.  I suspect it may have to do with the address computation or alignment

**Comment by zgu153522** [comment]
Just want to check and confirm what @smartbitcoin and @scchan are saying - if I *allocate* LDS as a multiple of 16 DWORDs (e.g. multiple of 64 bytes), but simply do not bother accessing the 'extra' amount, then this will work?  My tile size in terms of work items is already a multiple of wavefronts (1024) - it was just the LDS allocation and access that wasn't.

EDIT: this isn't working - it doesn't seem to matter if I allocated the LDS as a nice multiple of 64.  I have a more complicated test case for our application, and use integer multiples of wavefronts and declared the LDS array to have a multiple of 64 elements.  So perhaps it has to do with writing back to HBM some amount of elements that isn't a multiple of 64?

**Comment by zgu153522** [comment]
I checked through the generated ISA and am pretty sure I found a problem.  I am masking the store back to HBM using an if statement (e.g. only the first N idx.local store from LDS into HBM in order to not run over the LDS) but the compiler is not generating any exec mask for that.  So in my own user application I have 16 waves in the tile and need to store 2000 values to HBM using store, and then if (idx.local < 976) { store }, the ISA seems to say to store 2048.

**Comment by zgu153522** [comment]
I fixed this issue by manually inserting some ISA around the second store:
asm volatile("v_cmpx_gt_u32 vcc, 976, %0" : : "v"(idx.local[0]));
store instruction
asm volatile("s_not_b64 exec, 0" : : );

**Comment by scchan** [comment]
We've identified the problem that caused the problem in the ldsbug test case.  The compiler backend by default generates code to support kernel with a group size of 256 and it is aggressively optimizing code based on this information.  OpenCL has an attribute "reqd_work_group_size" to instruct the compiler to generate the correct code for a group size greater than the default size.  hcc has a similar function attribute [[hc_flat_workgroup_size(<group size>)]].  I've added [[hc_flat_workgroup_size(1024)]] to the ldsbug kernel and it's working fine.  Could you try that in your application?

**Comment by zgu153522** [comment]
Works, thank you!
