### ISSUE TITLE
mov_dpp combining with other instructions is not working

### ISSUE THREAD

**Issue by zgu153522** [RadeonOpenCompute/hcc#707]
Based on the GPUOpen blog article, HCC should do this:
Additionally, DPP is exposed as a special move instruction. The compiler will combine the DPP move with the subsequent instructions, if possible:

But it doesn't seem to be doing that.  I can force it with inline assembly, but there's no guarantee that HCC will put in the correct nops to avoid data hazards, and if I also inline the nops, most of the time they are unnecessary because I can just reorder instructions.

Also I would like to clarify that the row_mask and bank_mask arguments to amdgcn_move_dpp default to 0xf?  Based on the blog article, it looks like if you don't specify the argument in GCN, it'll default to all lanes enabled, but HCC seems to produce GCN code that will specify them as 0xf rather than leave out the argument.

**Comment by ex-rzr** [comment]
> Also I would like to clarify that the row_mask and bank_mask arguments to amdgcn_move_dpp default to 0xf? Based on the blog article, it looks like if you don't specify the argument in GCN, it'll default to all lanes enabled, but HCC seems to produce GCN code that will specify them as 0xf rather than leave out the argument.

I suppose there are two situation:
1) when you write asm code you can skip default values (0xf) for row_mask and bank_mask
2) but disasm always shows values for row_mask and bank_mask (including default)

Instructions are the same with manually passed 0xf and without *_mask at all (i.e. with default 0xf) as row_mask and bank_mask are always encoded in DPP instructions (I mean this doesn't make instructions longer): http://developer.amd.com/wordpress/media/2017/08/Vega_Shader_ISA_28July2017.pdf 13.3.9. DPP

Regarding the main issue: we didn't see such combining. And at first glance llvm doesn't have a code for that (or I was looking in the wrong place).

**Comment by zgu153522** [comment]
I tried to inline this but I get:
```
<inline asm>:1:31: error: invalid operand for instruction
        v_min_i32_e32 v23, v23, v24  quad_perm:[3,1,2,0]
                                     ^
note: !srcloc = 4770
Generating AMD GCN kernel failed in llc for target: gfx900
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
```
Seems it doesn't like the DPP modifiers?

**Comment by ex-rzr** [comment]
I would also try with `_dpp` suffix: `v_*_dpp`

**Comment by zgu153522** [comment]
Turns out to give more problems:
```
<inline asm>:1:43: error: unknown token in expression
        v_min_i32_e32_dpp v23, v23, v24 quad_perm:[3,1,2,0]
                                                 ^
note: !srcloc = 4724
<inline asm>:1:43: error: not a valid operand.
        v_min_i32_e32_dpp v23, v23, v24 quad_perm:[3,1,2,0]
                                                 ^
note: !srcloc = 4724
Generating AMD GCN kernel failed in llc for target: gfx900
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by zgu153522** [comment]
Fixed the inlining issue - I had e32 which I didn't realize was a suffix as well.  After replacing e32 with dpp it was working.  Closing this out because it's an enhancement and not an issue (although the GPUopen blog mentions the instruction combining feature).
