### ISSUE TITLE
Intrinsic name not mangled correctly for type arguments!

### ISSUE THREAD

**Issue by justxi** [RadeonOpenCompute/hcc#730]
I currently try to build the "roc-1.8.x" branch of hcc, but I get the following error:

[ 90%] Building OCL object rocdl/opencl/CMakeFiles/opencl_lib.dir/src/integer/add_sat.cl
cd /var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999_build/rocdl/opencl && /var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999_build/compiler/./bin/clang -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999_build/include -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/include -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/compiler/include -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/rocdl/opencl/src/integer -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/rocdl/opencl/src/workgroup -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/rocdl/opencl/../irif/inc -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/rocdl/opencl/../ocml/inc -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/rocdl/opencl/../ockl/inc -I/var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/rocdl/opencl/../oclc/inc  -o CMakeFiles/opencl_lib.dir/src/integer/add_sat.cl -Werror -x cl -Xclang -cl-std=CL2.0 -fblocks -target amdgcn-amd-amdhsa -DCL_VERSION_2_0=200 -D__OPENCL_C_VERSION__=200 -Dcl_khr_fp64 -Dcl_khr_fp16 -Dcl_khr_subgroups -Dcl_khr_int64_base_atomics -Dcl_khr_int64_extended_atomics -Xclang -finclude-default-header  -emit-llvm -c /var/tmp/portage/sys-devel/hcc-1.8.9999/work/hcc-1.8.9999/rocdl/opencl/src/integer/add_sat.cl
I**ntrinsic name not mangled correctly for type arguments! Should be: llvm.amdgcn.icmp.i32
i64 (i32, i32, i32)* @llvm.amdgcn.icmp.i64.i32
fatal error: error in backend: Broken function found, compilation aborted!**
clang-7.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)
HCC clang version 7.0.0 (86791fc4961dc8ffde77bde20d7dfa5e5cbeff5e) (0ccef158132e1222d549edf2da33d4bc0be6c2d1) (based on HCC 1.2.18175-6e93604c-86791fc496-0ccef158132 )
Target: amdgcn-amd-amdhsa
Thread model: posix

Building "rocm-1.7.x" and "head" worked two days ago.

**Comment by justxi** [comment]
The "ROCm-OpenCL-Runtime" (roc-1.8.x) seems to be affected by the same problem.

**Comment by scchan** [comment]
I wasn't able to reproduce this with hcc 1.7, 1.8 or the tip of our development branch.  Which distro do you have?  Have you tried cleaning up your build directory and try again?

**Comment by justxi** [comment]
Hi,
I use Gentoo Linux with self written ebuild (install script). I will checkout with git manually and try to compile it.

**Comment by perestoronin** [comment]
fixed with:

```
# cat irif.h.patch
--- a/ROCm-Device-Libs-roc-1.8.x/irif/inc/irif.h
+++ b/ROCm-Device-Libs-roc-1.8.x/irif/inc/irif.h
@@ -340,10 +340,10 @@
 extern __attribute__((const)) uint __llvm_amdgcn_sad_u16(uint, uint, uint) __asm("llvm.amdgcn.sad.u16");
 extern __attribute__((const)) uint __llvm_amdgcn_msad_u8(uint, uint, uint) __asm("llvm.amdgcn.msad.u8");

-extern __attribute__((const)) ulong __llvm_amdgcn_icmp_i32(uint, uint, uint) __asm("llvm.amdgcn.icmp.i64.i32");
-extern __attribute__((const)) ulong __llvm_amdgcn_icmp_i64(ulong, ulong, uint) __asm("llvm.amdgcn.icmp.i64.i64");
-extern __attribute__((const)) ulong __llvm_amdgcn_fcmp_f32(float, float, uint) __asm("llvm.amdgcn.fcmp.i64.f32");
-extern __attribute__((const)) ulong __llvm_amdgcn_fcmp_f64(double, double, uint) __asm("llvm.amdgcn.fcmp.i64.f64");
+extern __attribute__((const)) ulong __llvm_amdgcn_icmp_i32(uint, uint, uint) __asm("llvm.amdgcn.icmp.i32");
+extern __attribute__((const)) ulong __llvm_amdgcn_icmp_i64(ulong, ulong, uint) __asm("llvm.amdgcn.icmp.i64");
+extern __attribute__((const)) ulong __llvm_amdgcn_fcmp_f32(float, float, uint) __asm("llvm.amdgcn.fcmp.f32");
+extern __attribute__((const)) ulong __llvm_amdgcn_fcmp_f64(double, double, uint) __asm("llvm.amdgcn.fcmp.f64");

 extern __attribute__((const)) float __llvm_amdgcn_cubeid(float, float, float) __asm("llvm.amdgcn.cubeid");
 extern __attribute__((const)) float __llvm_amdgcn_cubema(float, float, float) __asm("llvm.amdgcn.cubema");
```

**Comment by perestoronin** [comment]
But clinfo hangs with more two Vega10 cards in Ryzen system

**Comment by justxi** [comment]
@perestoronin 

Interestingly if I checkout the code with "git clone --recursive -b roc-1.8.x https://github.com/RadeonOpenCompute/hcc.git" and build it, it works and the same lines which you have replaced are in the header file "irif.h".

But I thought that the git-r3 package should do the same as the "git" command...

**Comment by justxi** [comment]
It seems that the original problem is related to the checkout of the submodules. I changed the ebuild to use the proposed build steps and now it works. Due to the fact that the problems are not related to rocm/hcc I close this.
