### ISSUE TITLE
LLVM ERROR: Cannot select: intrinsic %llvm.amdgcn.ds.bpermute

### ISSUE THREAD

**Issue by lukeiwanski** [RadeonOpenCompute/hcc#754]
Hello,

First of all, thanks for the effort!

I run into the following linking error when trying out Eigen hip (https://github.com/ROCmSoftwarePlatform/eigen-upstream/pull/1).

``` make -j16 cxx11_tensor_device_hip
Linking HIP executable cxx11_tensor_device_hip
LLVM ERROR: Cannot select: intrinsic %llvm.amdgcn.ds.bpermute
Generating AMD GCN kernel failed in llc for target: gfx701
clang-7.0: error: linker command failed with exit code 1 (use -v to see invocation)
Died at /opt/rocm/bin/hipcc line 496.
unsupported/test/CMakeFiles/cxx11_tensor_device_hip.dir/build.make:667: recipe for target 'unsupported/test/cxx11_tensor_device_hip' failed
make[3]: *** [unsupported/test/cxx11_tensor_device_hip] Error 1
CMakeFiles/Makefile2:42853: recipe for target 'unsupported/test/CMakeFiles/cxx11_tensor_device_hip.dir/all' failed
make[2]: *** [unsupported/test/CMakeFiles/cxx11_tensor_device_hip.dir/all] Error 2
CMakeFiles/Makefile2:42860: recipe for target 'unsupported/test/CMakeFiles/cxx11_tensor_device_hip.dir/rule' failed
make[1]: *** [unsupported/test/CMakeFiles/cxx11_tensor_device_hip.dir/rule] Error 2
Makefile:185: recipe for target 'unsupported/test/CMakeFiles/cxx11_tensor_device_hip.dir/rule' failed
make: *** [unsupported/test/CMakeFiles/cxx11_tensor_device_hip.dir/rule] Error 2
```
cmake used for Eigen is

```
cmake -DEIGEN_TEST_HIP=1 -DEIGEN_TEST_CXX11=1 ..
```

My AMD GPU setup seems to be working (`clinfo` and `rocminfo` are reporting correct hardware) and the `HelloWorld` example from https://rocm.github.io/install.html returns values.

Do I need a specific version of the compiler?

Find verbose build log in here: https://gist.github.com/lukeiwanski/8520cd0e0902ec8da0ca14942e78bd9d

Thanks,

**Comment by whchung** [comment]
@lukeiwanski From the log it seems you are using a rather old AMD GPU, which is not officially support in ROCm project now:
```
Generating AMD GCN kernel failed in llc for target: gfx701
```
If I understand correctly bpermute intrinsic is not available on that particular instruction set. The earliest hardware supporting the intrinsic would be Fiji (gfx803).

**Comment by lukeiwanski** [comment]
@whchung thanks for the explanation.

Is there a way to specify the compilation target?

EDIT:
I found this flag
`-amdgpu-target=<value>  Specify AMDGPU ISA version (ex: gfx803). Could be specified only once.` 

However it seems like  `hcc` adds the existing hardware to the target array. See verbose log:  https://gist.github.com/lukeiwanski/e9283125bf7a26ef122b67b6c6a84acc

Is there a way to compile / link for only specific target that is not present in the system? (sort of cross-compilation if you will)

**Comment by aaronenyeshi** [comment]
@lukeiwanski https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/lib/clamp-link.in#L41 There are 3 ways to specify the compilation target from what I know. So for your case, you'd probably want to set HCC_AMDGPU_TARGET env var to override.

**Comment by lukeiwanski** [comment]
Fantastic! Thanks guys!
