### ISSUE TITLE
Compiling with HCC/HIPCC results in empty .kernel section.

### ISSUE THREAD

**Issue by Jorghi12** [RadeonOpenCompute/hcc#756]
I'm currently compiling kernels using HIPCC and notice that the kernel section is empty. Essentially, this command returns an empty file named kernel_section.bc.

`objcopy -O binary -j .kernel ./build/caffe2/CMakeFiles/caffe2_hip.dir/__/aten/src/THC/caffe2_hip_generated_THCTensorMathPairwise.cu.o kernel_section.bc
`
Thus, it appears that there are issues during the compilation stage with HIPCC. Any ideas why kernels bitcode isn't being generated at all?

**Comment by whchung** [comment]
Per discussion this is not a compiler issue but an configuration issue.
