### ISSUE TITLE
HCC should exit with error when Linking error occurs.

### ISSUE THREAD

**Issue by Jorghi12** [RadeonOpenCompute/hcc#757]
When linking with HCC, on the error "symbol multiply defined", the shared library is still produced but with zero device code. Better practice is to exit gracefully before this happens.

Another question, why aren't (ret=$?) values provided for every single branch in the if block [here](https://github.com/RadeonOpenCompute/hcc/blob/master/lib/clamp-link.in#L610)? I'm pretty sure the GNU linker ld will always provide a return value.

**Comment by aaronenyeshi** [comment]
Your link is reference the master branch. We are using clang_tot_upgrade as latest HEAD. Also, it seems that in PR#837, the shared library is no longer produced. I will close this, please reopen if its still reproducible.
