### ISSUE TITLE
rocm 1.1 device query?

### ISSUE THREAD

**Issue by psteinb** [RadeonOpenCompute/hcc#76]
Hi, 
I am using rocm `4.4.0-kfd-compute-rocm-rel-1.1.1-10` and wanted to write a simple device query app with hc:

```
void print_device_info(hc::accelerator& acc){
   std::cout << "\tname:" << acc.get_description().c_str() << "\n";
  std::cout << "\tmem :" << acc.get_dedicated_memory() << "\n";
  std::cout << "\tvers:" << acc.get_version() << "\n";
 }

int main(int argc, char *argv[])
{
std::vector<accelerator> accs = accelerator::get_all();
for ( size_t i = 0; i < accs.size();++i){
      std::cout << "devid: " << i << " / "<< accs.size()<<"\n";
      print_device_info(accs[i]);
    }
return 0;
}
```
The output I am getting on a R730 with 2xE5-2620v3 and 1x S9300x2 is:
```
devid: 0 / 3
        name:0x7f7fd1dbcc20
        mem :0
        vers:0
devid: 1 / 3
        name:0x7f7fd1dbbbb0
        mem :0
        vers:0
devid: 2 / 3
        name:0x7f7fd1dbbbb0
        mem :0
        vers:0
```
Am I using the API wrong or is the driver not ready yet?
Best -

**Comment by whchung** [comment]
@psteinb hc::accelerator::get_description() returns std::wstring . So you'll need to use std::wcout instead of std::out .

**Comment by psteinb** [comment]
good catch, but that doesn't explain the "0" with the other functions.

**Comment by psteinb** [comment]
also, what is the rational behind a wide string for `get_description()`? Do you expect any non-ASCII characters in device names?

**Comment by whchung** [comment]
```hc.hpp``` was derived from C++AMP, and it C++AMP specification and the interface is defined to return ```std::wstring```.

```hc::accelerator::get_dedicated_memory()``` and ```hc::accelerator::get_version()``` have only dummy implementation right now. Let me fix them, as it seems memory region / pool API in HSA runtime have been stabilized.

**Comment by psteinb** [comment]
very good, thanks a bunch. I am not sure about others reading this thread, but when I start working with a new parallel programming paradigm/environment introspection of hardware is always a nice playground. before I close this thread, is there any way to infer the amount of available memory through HCC?

**Comment by whchung** [comment]
Please leave this thread open for now, as there's indeed no API to query device memory via HCC at this moment.

I'm going to refactor [HIP runtime](https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP/blob/master/src/hip_hcc.cpp#L625), so a proper dependency is formed between HIP/HCC/HSA.

**Comment by whchung** [comment]
@psteinb I've made a few commits on "develop" branch of hcc. Now HCC runtime should be able to report version string and device memory for HSA agents:

```
$ ./a.out 
devid: 0 / 2
	name:CPU Device
	mem :0
	vers:0
devid: 1 / 2
	name:AMD HSA Agent Fiji1
	mem :4294967296
	vers:65536
```

**Comment by psteinb** [comment]
Very good, I'll have a look in due course.
Thanks
