### ISSUE TITLE
HCC issue creating kernel. Assigns R_X86_64_GOTPCREL symbol type.

### ISSUE THREAD

**Issue by Jorghi12** [RadeonOpenCompute/hcc#780]
Hi! When using HCC to build my device code, all of my kernels work except for one in particular.

When I use objdump to view the symbol information, I see this:
`000000000014728 R_X86_64_GOTPCREL  _ZN2at4cuda21kernelPointwiseApply3IZNS_6native31hardshrink_backward_cuda_kernelIdEEvRNS_6TensorEPT_RKS4_S9_EUlRdSA_SA_E_dddjLi1ELi1ELi1EEEvNS0_6detail10TensorInfoIT0_T3_EENSD_IT1_SF_EENSD_IT2_SF_EESF_S6_-0x0000000000000004`

And I also see this for some of them:
`0000000000023db0  w    F .text  0000000000000009 _ZN2at4cuda21kernelPointwiseApply3IZNS_6native31hardshrink_backward_cuda_kernelINS_4HalfEEEvRNS_6TensorEPT_RKS5_SA_EUlRS4_SB_SB_E_S4_S4_S4_jLi1ELi2ELi2EEEvNS0_6detail10TensorInfoIT0_T3_EENSE_IT1_SG_EENSE_IT2_SG_EESG_S7_
`

What's strange is that I have the kernels defined for these functions already.

**Comment by scchan** [comment]
Could you say more about how/why that kernel doesn't work and provide a repro test case please?
