### ISSUE TITLE
Issue with symbol requiring -fPIC when Linking with HCC.

### ISSUE THREAD

**Issue by Jorghi12** [RadeonOpenCompute/hcc#790]
The error message says I should recompile with "-fPIC". What exactly am I supposed to recompile?

The symbol **hiprng_uniform** is defined in the hcRNG package, which is already built with -fPIC based off the CMAKE_CXX_FLAGS: https://github.com/ROCmSoftwarePlatform/hcRNG/blob/master/build.sh#L180.

Also, -fPIC is always being passed to the hcc compiler when producing the object files that contain these symbols.

```
/opt/rocm/hcc/bin/ld.lld: error: relocation R_AMDGPU_REL32_LO cannot be used against symbol hiprng_uniform; recompile with -fPIC
>>> defined in /tmp/tmp.XEZurr46Ah/kernel-gfx900.hsaco.isabin
>>> referenced by /tmp/tmp.XEZurr46Ah/kernel-gfx900.hsaco.isabin:(generate_cauchy(hcrngStateMtgp32*, int, __half*, double, double))

/opt/rocm/hcc/bin/ld.lld: error: relocation R_AMDGPU_REL32_HI cannot be used against symbol hiprng_uniform; recompile with -fPIC
>>> defined in /tmp/tmp.XEZurr46Ah/kernel-gfx900.hsaco.isabin
>>> referenced by /tmp/tmp.XEZurr46Ah/kernel-gfx900.hsaco.isabin:(generate_cauchy(hcrngStateMtgp32*, int, __half*, double, double))
```

**Comment by nvlbal** [comment]
What did you do to resolve this issue?
I am finding the same when calling __bitselect_b64
