### ISSUE TITLE
HCC Compiler doesn't replace std math functions

### ISSUE THREAD

**Issue by Jorghi12** [RadeonOpenCompute/hcc#801]
From what I've read, it appears that HCC aims to be primarily a standard C++ Compiler. 

It appears that the NVCC Compiler recognizes all uses of std::abs / std::exp / etc functions within device code and replaces them with the CUDA equivalent functions.

It's a very helpful feature that simplifies the porting of pre-existing projects /  less overhead when writing future kernels. 

Could we have this behavior brought into HCC as well?

**Comment by Jorghi12** [comment]
@whchung @mangupta

**Comment by AlexVlx** [comment]
This is a HIP issue, as HIP concerns itself with mimicking CUDA behaviour. Upcoming HIP changes will model this behaviour (I do not have an ETA for those however).
