### ISSUE TITLE
[roc-1.8.x] Uses outdated submodules, leading to build error.

### ISSUE THREAD

**Issue by Jorghi12** [RadeonOpenCompute/hcc#817]
Building the roc-1.8.x branch leads to the error below even when cloning the repository and its various submodules recursively via git recursive.

`git clone --recursive -b roc-1.8.x https://github.com/RadeonOpenCompute/hcc.git`

```
[ 98%] Built target mcwamp_hsa
Intrinsic name not mangled correctly for type arguments! Should be: llvm.amdgcn.icmp.i32
i64 (i32, i32, i32)* @llvm.amdgcn.icmp.i64.i32
fatal error: error in backend: Broken function found, compilation aborted!
clang-7.0: error: clang frontend command failed with exit code 70 (use -v to see invocation)
```

In order to successfully build, I had to open the "rocdl/irif/inc/irif.h" file and make these several changes below. So I'm assuming that the submodules that were automatically downloaded via git are outdated.

```
-extern __attribute__((const)) ulong __llvm_amdgcn_icmp_i32(uint, uint, uint) __asm("llvm.amdgcn.icmp.i64.i32");
-extern __attribute__((const)) ulong __llvm_amdgcn_icmp_i64(ulong, ulong, uint) __asm("llvm.amdgcn.icmp.i64.i64");
-extern __attribute__((const)) ulong __llvm_amdgcn_fcmp_f32(float, float, uint) __asm("llvm.amdgcn.fcmp.i64.f32");
-extern __attribute__((const)) ulong __llvm_amdgcn_fcmp_f64(double, double, uint) __asm("llvm.amdgcn.fcmp.i64.f64");
+extern __attribute__((const)) ulong __llvm_amdgcn_icmp_i32(uint, uint, uint) __asm("llvm.amdgcn.icmp.i32");
+extern __attribute__((const)) ulong __llvm_amdgcn_icmp_i64(ulong, ulong, uint) __asm("llvm.amdgcn.icmp.i64");
+extern __attribute__((const)) ulong __llvm_amdgcn_fcmp_f32(float, float, uint) __asm("llvm.amdgcn.fcmp.f32");
+extern __attribute__((const)) ulong __llvm_amdgcn_fcmp_f64(double, double, uint) __asm("llvm.amdgcn.fcmp.f64");
```

**Comment by aaronenyeshi** [comment]
@b-sumner

**Comment by Jorghi12** [comment]
@b-sumner @aaronenyeshi 

After building HCC, I'm now trying to build HIP and receive this error:

Since I've been able to build HIP using the HCC package provided by the official ROCm apt repository, I'm assuming something must have went wrong with my installation of HCC. Any ideas?

`/opt/rocm/hcc/bin/../lib/libhc_am.so: undefined symbol: _ZNSt3__15ctypeIcE2idE`

**Comment by Jorghi12** [comment]
@b-sumner @aaronenyeshi 

After building HCC, I now receive this error. 

`/opt/rocm/hcc/bin/../lib/libhc_am.so: undefined symbol: _ZNSt3__15ctypeIcE2idE`

From researching, this issue is caused by having differing versions of dependency packages / etc. The instructions provided on the HCC wiki appear to be outdated since they're not solving my issue.

Could I have a list of all the dependency packages (and versions) that were used to build the HCC package released in the ROCm apt repository? Thanks!

**Comment by aaronenyeshi** [comment]
You seem to be on a different branch on rocdl: https://github.com/RadeonOpenCompute/ROCm-Device-Libs/blob/master/irif/inc/irif.h#L346 This is the master of the public version

**Comment by Jorghi12** [comment]
@aaronenyeshi Hi, I've updated all branches to those specified over here: https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/.gitmodules) but still receive build errors.

Could you provide a Debian package for HCC roc-1.8.x that has the debugging features enabled? Thanks!

https://github.com/RadeonOpenCompute/hcc/blob/master/lib/hsa/mcwamp_hsa.cpp#L42
```
#define KALMAR_DEBUG (1)
#define KALMAR_DEBUG_ASYNC_COPY (1)
```

**Comment by Jorghi12** [comment]
Resolved by forcing it not to use LIBCXX https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/CMakeLists.txt#L178.

**Comment by scchan** [comment]
We don't use LIBCXX by default on platforms we support.  On what OS you are building hcc on?
