### ISSUE TITLE
[Request] Debian package for HCC roc-1.8.x with Debugging Features Enabled.

### ISSUE THREAD

**Issue by Jorghi12** [RadeonOpenCompute/hcc#821]
Hi, I'd like a package for HCC roc-1.8.x that has the debugging features below enabled. Thanks!

https://github.com/RadeonOpenCompute/hcc/blob/master/lib/hsa/mcwamp_hsa.cpp#L42
```
#define KALMAR_DEBUG (1)
#define KALMAR_DEBUG_ASYNC_COPY (1)
```

**Comment by Jorghi12** [comment]
@whchung @scchan @aaronenyeshi @AlexVlx @kwu91 @bensander @lyh-kernel-MCW @rocm-hcc @pfultz2 @tstellarAMD @facao @sunway513

**Comment by jithunnair-amd** [comment]
@Jorghi12 Can you please elaborate here why you were not able to build the hcc package on your end with debugging enabled?

**Comment by Jorghi12** [comment]
After installing HCC, I end up with this error in the libmcwamp_cpu.so library.
It looks like perhaps libc++ and libstdc++ are being mixed up in the HCC installation?

```
C++AMP runtime load error: /opt/rocm/hcc/bin/../lib/libmcwamp_cpu.so: undefined symbol: _ZNSt3__119__shared_weak_countD2Ev
Can't load CPU runtime!
```

**Comment by Jorghi12** [comment]
Resolved by forcing it not to use LIBCXX https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/CMakeLists.txt#L178.

**Comment by scchan** [comment]
The extra debug messages will be enabled by this PR: https://github.com/RadeonOpenCompute/hcc/pull/824
