### ISSUE TITLE
Segmentation fault when accessing hc::array by integer index from cpu

### ISSUE THREAD

**Issue by misos1** [RadeonOpenCompute/hcc#835]
This throws exception as per documentation "Accessing array data on a location where it is not resident (e.g. from the CPU when it is resident on a GPU) results in an exception (in cpu context)":
``` c++
hc::array<int> arr(1);
try
{
	printf("%i\n", arr[hc::index<1>(0)]);
}
catch(std::exception &e)
{
	printf("%s\n", e.what()); // The array is not accessible on CPU.
}
```
But this causes segmentation fault:
``` c++
hc::array<int> arr(1);
try
{
	printf("%i\n", arr[0]);
}
catch(std::exception &e)
{
	printf("%s\n", e.what());
}
```
Difference is that in hc.hpp `hc::array::operator[](int)` does not check pointer as `hc::array::operator[](hc::index)` does.

**Comment by scchan** [comment]
hc::array is a device memory buffer so it cannot be directly accessed from the CPU.  
You either need an hc::array_view wrapped around an hc::array or do a copy from hc::array into a CPU buffer in order to access the data on the CPU

**Comment by misos1** [comment]
The point was that it should throw exception instead of segmentation fault in case of integral index as it does when passing hc::index.

**Comment by scchan** [comment]
I have a patch for the segfault: https://github.com/RadeonOpenCompute/hcc/pull/838
