### ISSUE TITLE
Function template specialisation causes error "symbol multiply defined!"

### ISSUE THREAD

**Issue by misos1** [RadeonOpenCompute/hcc#837]
func.hpp:
``` c++
#include <hc.hpp>
template<typename T, int N>
void func(const hc::array_view<T, N> &view)
{
}
template<>
void func(const hc::array_view<int, 2> &view)
{
}
```
main.cpp:
``` c++
#include "func.hpp"
int main()
{
	hc::array_view<int, 2> arr(1);
	func(arr);
	parallel_for_each(hc::extent<1>(1), []() [[hc]]
	{
	});
	return 0;
}
```
a.cpp:
``` c++
#include "func.hpp"
```
Compiling using ``hcc main.cpp a.cpp `hcc-config --cxxflags --ldflags` `` prints error:
```
ERROR: Linking globals named '_Z4funcIiLi2EEvRKN2hc10array_viewIT_XT0_EEE': symbol multiply defined!
```
Output binary is generated but seems it cannot run kernels:
```
HSADevice::CreateKernel(): Unable to create kernel main::$_0::__cxxamp_trampoline 
  CreateKernel_raw=  _ZZ4mainEN3$_019__cxxamp_trampolineEv
  CreateKernel_demangled=  main::$_0::__cxxamp_trampoline()
Aborted (core dumped)
```
When is `func` restricted with `[[cpu]]` or func.hpp is not included in a.cpp then there is no error.

**Comment by misos1** [comment]
Ok there are indeed multiple definitions of specialised `func` so it violates one definition rule (it need to be in .cpp file or declared inline) but why is this not problem also for host compilation phase?

**Comment by PhilipDeegan** [comment]
I'm seeing this too, linking should fail, but appears to succeed even with multiple definitions

**Comment by PhilipDeegan** [comment]
this is a duplicate of https://github.com/RadeonOpenCompute/hcc/issues/757

**Comment by david-salinas** [comment]
@misos1 and @Dekken  : With latest rocm 1.9, I'm seeing the expected link error, but no binary is generated.  Can you confirm?  thanks.

**Comment by misos1** [comment]
Yes seems binary is not generated now.
