### ISSUE TITLE
two step compile/link runtime failure

### ISSUE THREAD

**Issue by PhilipDeegan** [RadeonOpenCompute/hcc#842]
Looking at the following example: http://pastebin.com/raw/mD7KY1pu

It seems to be mandatory for binary object files to have the filetype ".o" in order to work properly, this seems a bit strange to me

this is a follow up from https://github.com/RadeonOpenCompute/hcc/issues/138

**Comment by vsytch** [comment]
If you want to use files with .obj extension you'll have to change the "o" to "obj" in this line https://github.com/RadeonOpenCompute/hcc-clang-upgrade/blob/clang_tot_upgrade/include/clang/Driver/Types.def#L105

**Comment by PhilipDeegan** [comment]
is there some more behind this? 

what is the reason for it's existence, why should it be needed?

Thanks

**Comment by vsytch** [comment]
The extension is there to tell the compiler what kind of file you are giving it. The .o extension is the commonly one used for object files on Linux, .obj is the Windows analogous.

**Comment by PhilipDeegan** [comment]
the file extension is arbitrary, and shouldn't matter

**Comment by b-sumner** [comment]
gcc won't give me an object file if I compile a file named "source.xyz" containing correct C code.  I think there is precedent for compilers and tools to require certain extensions on files with certain contents.

**Comment by vsytch** [comment]
The .o extension is also hardcoded in the the hcc linker scripts (under https://github.com/RadeonOpenCompute/hcc/tree/clang_tot_upgrade/lib), because that's the standard extension on Linux. Too use the .obj extension you'd also have to change those as well as changing clang.

**Comment by PhilipDeegan** [comment]
fair enough, guess it goes beyond HCC, peculiar, when file extensions aren't supposed to even matter on Linux
