### ISSUE TITLE
Linker can't relocate against symbols

### ISSUE THREAD

**Issue by j-stephan** [RadeonOpenCompute/hcc#845]
Minimal example:

    #include <hc.hpp>

    auto main() -> int
    {
        auto array = hc::array<int, 1>{hc::extent<1>{1024}};

        hc::parallel_for_each(array.get_extent().tile(64),
                              [=, &array](hc::tiled_index<64> tile_index) [[hc]] {});

        return 0;
    }

Compiler command line:

    hcc `hcc-config --cxxflags --ldflags` -std=c++17 -fPIC -O3 minimal.cpp -o minimal

Varying the C++ standard and/or removing fPIC does not make any difference.

Error message:

    /opt/rocm/hcc/bin/ld.lld: error: relocation R_AMDGPU_REL32_LO cannot be used against symbol hc::tiled_index<64>::til
    >>> defined in /tmp/tmp.apOktdPX1x/kernel-gfx900.hsaco.isabined_index(); recompile with -fPIC
    >>> referenced by /tmp/tmp.apOktdPX1x/kernel-gfx900.hsaco.isabin:(main::$_0::__cxxamp_trampoline(int*, int, int))

Operating system:

    $ cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
    $ uname -a
    Linux hostname 4.15.0-32-generic #35~16.04.1-Ubuntu SMP Fri Aug 10 21:54:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I'm using the open source ROCm stack (installed from the repositories) with a Vega 64, no closed source driver. I also didn't install any additional packages (e.g. compilers or so), the system is a plain, fresh Ubuntu installation.

**Comment by scchan** [comment]
`hc::tiled_index<64>`  The template argument is the number of dimensions in a tile/index, in this case, it should be 1 instead of 64

**Comment by j-stephan** [comment]
Yup, that's it! Thanks for the hint. However, the error message is rather cryptic, is it possible to improve it?
