### ISSUE TITLE
rocm 1.9 gives spurious message on ubuntu 18.04 on saxpy example from the wiki

### ISSUE THREAD

**Issue by mvermeulen** [RadeonOpenCompute/hcc#874]
Compiling the saxpy example with "hcc `hcc-config --cxxflags --ldflags` saxpy.cpp -o saxpy" results in the following message:
objdump: /usr/lib/x86_64-linux-gnu/libm.a: File format not recognized.

What appears to be going on is:
1. clamp-link has a call to detect .kernel sections in static libraries, i.e. objdump -t $DETECTED_STATIC_LIBRARY | grep -q "\.kernel"

2. On ubuntu 18.04, the particular file /usr/lib/x86_64-linux/gnu/libm.a is a linker script with following contents:
/* GNU ld script
*/
OUTPUT_FORMAT(elf64-x86_64)
GROUP ( /usr/lib/x86_64-linux-gnu/libm-2.27.a /usr/lib/x86_64-linux-gnu/libmvec.a )
The combination of objdump and clamp-link expects archive libraries and not linker scripts.

Assume the message is benign since system libraries are not expected to have .kernel symbols, but report it as a spurious message.

**Comment by JMadgwick** [comment]
I can confirm that I saw this myself yesterday when compiling a program which I had compiled before on 16.04 before updating to 18.04. When I compiled on 16.04 there was no message or output at all from hcc. The program still compiles and fine exactly as it did before. I imagine this message will be seen when compiling anything that uses hc sections?

**Comment by david-salinas** [comment]
Yes, this message is benign, but noisy.  There may be a more elegant way for clamp-link to search for kernel sections in libraries that may in fact just be linker scripts.

**Comment by aaronenyeshi** [comment]
Please verify that this is fixed with https://github.com/RadeonOpenCompute/hcc/pull/914 . Reopen if it still persists
