### ISSUE TITLE
std::bad_function_call error on examples in simple program

### ISSUE THREAD

**Issue by Plumax** [RadeonOpenCompute/hcc#88]
Hello everyone

I installed the hcc compiler using debian rep. I tried to run a little example to test if I'm able to use it properly.

Here's my code:

```
#include <hc.hpp>
#include <iostream>
using namespace concurrency;

int main(int argc, char ** argv)
{


	char c;
	std::cin >> c;

	return 0;
}
```

And then, I build it as shown in the doc:
`hcc `hcc-config --cxxflags --ldflags` ../src/_SandboxTEST/test.cpp -o test`

However, when I'm trying to run the result `./test`, I got:

```
terminating with uncaught exception of type std::bad_function_call: bad_function_call
Abandon
```

Is anybody have an idea of what it can be?

Thank you

Plumax

**Comment by whchung** [comment]
@Plumax could you share me your machine configuration (CPU / MB / GPU / Linux distro / kernel version / ROCm stack version)?

**Comment by Plumax** [comment]
I got : 

- CPU :  double processor Intel Xeon E5-2630 v3
- MB : 16 Go memory DDR3
- GeForce GTX 480
- Distro : Linux Mint 17.3
-  kernel version: 3.19.0-32-generic
- ROCm : 1.1.1 package

**Comment by whchung** [comment]
It seems your configuration isn't supported right now:
- GeForce GTX 480 : it doesn't support either HSAIL or AMD GCN. You could try install CUDA SDK and let hcc be built using its OpenCL stack though.
- Linux Mint 17.3 : it's suggested to use Ubuntu 14.04 or 16.04
- ROCm : ROCm only works on AMD GPU, and your kernel version (3.19.0-32) suggests ROCm stack isn't properly installed (uname -a should show something like 4.4.0-kfd-compute-rocm-rel-x.x)
