### ISSUE TITLE
Strange unrolling of loop with barrier when work group size is greater than 256

### ISSUE THREAD

**Issue by misos1** [RadeonOpenCompute/hcc#901]
I encountered this when tried to simplify different case.

``` c++
hc::array_view<int> a(512);
parallel_for_each(hc::tiled_extent<1>(512, 512), [=](hc::tiled_index<1> i) [[hc]]
{
	tile_static int x;
	int wid = i.local[0] / 64;
	int cnt = 0;
	//#pragma nounroll
	for(int k = 0; k < 8; k++)
	{
		if(wid == k)x = wid;
		i.barrier.wait_with_tile_static_memory_fence();
		if(wid == k && x == wid)cnt++;
	}
	a[i.local[0]] = cnt;
});

for(int i = 0; i < 512; i += 64)
{
	printf("%3i  ", i);
	for(int j = 0; j < 64; j++)
		printf("%i", a[i + j]);
	printf("\n");
}
```

This should print all ones but instead I am getting this:

```
  0  1111111111111111111111111111111111111111111111111111111111111111
 64  1111111111111111111111111111111111111111111111111111111111111111
128  1111111111111111111111111111111111111111111111111111111111111111
192  1111111111111111111111111111111111111111111111111111111111111111
256  0000000000000000000000000000000000000000000000000000000000000000
320  0000000000000000000000000000000000000000000000000000000000000000
384  0000000000000000000000000000000000000000000000000000000000000000
448  0000000000000000000000000000000000000000000000000000000000000000
```

It is working as expected when I uncomment line with "#pragma nounroll" or when using unroll with depth 2 or 4.

Here is asm. Strange are 4 s_barrier instructions in a row near bottom like there is missing something. Like it was unrolled 4 times and then from rest extracted only s_barrier instructions like compiler decided that i.local[0] will be never greater than 256.

<details><summary>1. assembler</summary>
<pre>
	v_lshrrev_b32_e32 v3, 6, v0
	v_mov_b32_e32 v4, 0
	v_cmp_ne_u32_e32 vcc, 0, v3
	v_mov_b32_e32 v5, 0
                                        ; implicit-def: $vgpr1
                                        ; implicit-def: $vgpr2
	s_and_saveexec_b64 s[0:1], vcc
	s_xor_b64 s[0:1], exec, s[0:1]
	; mask branch BB0_4
	s_cbranch_execz BB0_4
BB0_1:                                  ; %for.inc.i
	s_barrier
	v_cmp_eq_u32_e32 vcc, 1, v3
	v_mov_b32_e32 v5, -1
	v_mov_b32_e32 v4, 0
                                        ; implicit-def: $vgpr1
	s_and_saveexec_b64 s[2:3], vcc
	s_xor_b64 s[2:3], exec, s[2:3]
	; mask branch BB0_3
BB0_2:                                  ; %for.inc.i.1.thread
	v_mov_b32_e32 v1, 1
	v_mov_b32_e32 v5, 0
	ds_write_b32 v5, v1
	s_waitcnt lgkmcnt(0)
	s_barrier
	ds_read_b32 v1, v5
	v_mov_b32_e32 v4, -1
	s_waitcnt lgkmcnt(0)
	v_cmp_eq_u32_e32 vcc, 1, v1
	v_cndmask_b32_e64 v1, 0, 1, vcc
BB0_3:                                  ; %Flow1
	s_or_b64 exec, exec, s[2:3]
	v_mov_b32_e32 v2, 0
BB0_4:                                  ; %Flow
	s_or_saveexec_b64 s[0:1], s[0:1]
	s_xor_b64 exec, exec, s[0:1]
	; mask branch BB0_6
BB0_5:                                  ; %for.inc.i.thread
	v_mov_b32_e32 v2, 0
	ds_write_b32 v2, v2
	s_waitcnt lgkmcnt(0)
	s_barrier
	ds_read_b32 v2, v2
	v_mov_b32_e32 v5, -1
	s_waitcnt lgkmcnt(0)
	v_cmp_eq_u32_e32 vcc, 0, v2
	v_cndmask_b32_e64 v2, 0, 1, vcc
BB0_6:                                  ; %Flow2
	s_or_b64 exec, exec, s[0:1]
	v_mov_b32_e32 v6, 0
	v_cmp_ne_u32_e32 vcc, 0, v5
	s_and_saveexec_b64 s[0:1], vcc
	; mask branch BB0_8
BB0_7:                                  ; %for.inc.i.1
	s_barrier
	v_cmp_ne_u32_e32 vcc, 2, v3
	v_mov_b32_e32 v6, -1
	v_cndmask_b32_e64 v4, 0, -1, vcc
	v_mov_b32_e32 v1, v2
BB0_8:                                  ; %Flow3
	s_or_b64 exec, exec, s[0:1]
	v_cmp_ne_u32_e32 vcc, 0, v4
	v_mov_b32_e32 v5, 0
                                        ; implicit-def: $vgpr4
	s_and_saveexec_b64 s[0:1], vcc
	; mask branch BB0_12
	s_cbranch_execz BB0_12
BB0_9:                                  ; %for.inc.i.2
	s_barrier
	v_cmp_eq_u32_e32 vcc, 3, v3
	v_mov_b32_e32 v5, -1
                                        ; implicit-def: $vgpr4
	s_and_saveexec_b64 s[2:3], vcc
	s_xor_b64 s[2:3], exec, s[2:3]
	; mask branch BB0_11
BB0_10:                                 ; %for.inc.i.3.thread
	v_mov_b32_e32 v3, 3
	v_mov_b32_e32 v5, 0
	ds_write_b32 v5, v3
	s_waitcnt lgkmcnt(0)
	s_barrier
	ds_read_b32 v3, v5
	s_waitcnt lgkmcnt(0)
	v_cmp_eq_u32_e32 vcc, 3, v3
	v_addc_co_u32_e32 v4, vcc, 0, v1, vcc
BB0_11:                                 ; %Flow5
	s_or_b64 exec, exec, s[2:3]
	v_mov_b32_e32 v6, 0
BB0_12:                                 ; %Flow4
	s_or_b64 exec, exec, s[0:1]
	s_load_dwordx2 s[0:1], s[4:5], 0x0
	v_cmp_ne_u32_e32 vcc, 0, v6
	s_and_saveexec_b64 s[2:3], vcc
	; mask branch BB0_14
BB0_13:                                 ; %for.inc.i.2.thread
	v_mov_b32_e32 v1, 2
	v_mov_b32_e32 v3, 0
	ds_write_b32 v3, v1
	s_waitcnt lgkmcnt(0)
	s_barrier
	ds_read_b32 v1, v3
	v_mov_b32_e32 v5, -1
	s_waitcnt lgkmcnt(0)
	v_cmp_eq_u32_e32 vcc, 2, v1
	v_addc_co_u32_e32 v1, vcc, 0, v2, vcc
BB0_14:                                 ; %Flow6
	s_or_b64 exec, exec, s[2:3]
	s_load_dword s2, s[4:5], 0x18
	s_load_dword s4, s[4:5], 0x20
	v_cmp_ne_u32_e32 vcc, 0, v5
	s_and_saveexec_b64 s[6:7], vcc
	; mask branch BB0_16
BB0_15:                                 ; %for.inc.i.3
	s_waitcnt lgkmcnt(0)
	s_barrier
	v_mov_b32_e32 v4, v1
BB0_16:                                 ; %for.inc.i.7
	s_or_b64 exec, exec, s[6:7]
	s_waitcnt lgkmcnt(0)
	<b>s_barrier
	s_barrier
	s_barrier
	s_barrier</b>
	v_lshlrev_b32_e32 v0, 2, v0
	v_mov_b32_e32 v1, s1
	v_add_co_u32_e32 v0, vcc, s0, v0
	s_ashr_i32 s5, s4, 31
	s_lshl_b64 s[0:1], s[4:5], 2
	v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
	v_mov_b32_e32 v2, s1
	v_add_co_u32_e32 v0, vcc, s0, v0
	s_ashr_i32 s3, s2, 31
	v_addc_co_u32_e32 v1, vcc, v1, v2, vcc
	s_lshl_b64 s[0:1], s[2:3], 2
	v_mov_b32_e32 v2, s1
	v_add_co_u32_e32 v0, vcc, s0, v0
	v_addc_co_u32_e32 v1, vcc, v1, v2, vcc
	global_store_dword v[0:1], v4, off
	s_endpgm
</pre>
</details>

<br/>
It is same also for this:

``` c++
hc::array_view<int> a(512);
parallel_for_each(hc::tiled_extent<1>(512, 512), [=](hc::tiled_index<1> i) [[hc]]
{
	int cnt = 0;
	for(int k = 0; k < 8; k++)
	{
		i.barrier.wait_with_tile_static_memory_fence();
		if(i.local[0] / 64 == k)cnt++;
	}
	a[i.local[0]] = cnt;
});
```

<details><summary>2. assembler</summary>

``` asm
	s_barrier
	s_barrier
	s_barrier
	s_barrier
	s_barrier
	s_barrier
	s_barrier
	s_barrier
	s_load_dwordx2 s[0:1], s[4:5], 0x0
	v_lshrrev_b32_e32 v1, 6, v0
	v_cmp_eq_u32_e32 vcc, 1, v1
	v_lshlrev_b32_e32 v0, 2, v0
	s_load_dword s2, s[4:5], 0x18
	s_load_dword s4, s[4:5], 0x20
	v_cndmask_b32_e64 v3, 0, 1, vcc
	s_waitcnt lgkmcnt(0)
	v_mov_b32_e32 v2, s1
	v_add_co_u32_e32 v0, vcc, s0, v0
	v_addc_co_u32_e32 v2, vcc, 0, v2, vcc
	v_cmp_eq_u32_e32 vcc, 0, v1
	v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
	v_cmp_eq_u32_e32 vcc, 2, v1
	s_ashr_i32 s5, s4, 31
	v_cndmask_b32_e64 v5, 0, 1, vcc
	v_cmp_eq_u32_e32 vcc, 3, v1
	s_lshl_b64 s[4:5], s[4:5], 2
	v_addc_co_u32_e32 v3, vcc, v3, v5, vcc
	s_ashr_i32 s3, s2, 31
	v_mov_b32_e32 v4, s5
	v_add_co_u32_e32 v0, vcc, s4, v0
	s_lshl_b64 s[0:1], s[2:3], 2
	v_addc_co_u32_e32 v1, vcc, v2, v4, vcc
	v_mov_b32_e32 v2, s1
	v_add_co_u32_e32 v0, vcc, s0, v0
	v_addc_co_u32_e32 v1, vcc, v1, v2, vcc
	global_store_dword v[0:1], v3, off
	s_endpgm
```

</details>

<br/>
And without barrier (at some cycle k will be 4 so work items from 256 to 319 should also set 1):

``` c++
hc::array_view<int> a(512);
parallel_for_each(hc::tiled_extent<1>(512, 512), [=](hc::tiled_index<1> i) [[hc]]
{
	int cnt = 0;
	for(int k = 0; k < 8; k++)
	{
		if(i.local[0] / 64 == k)cnt++;
	}
	a[i.local[0]] = cnt;
});
```

```
  0  1111111111111111111111111111111111111111111111111111111111111111
 64  1111111111111111111111111111111111111111111111111111111111111111
128  1111111111111111111111111111111111111111111111111111111111111111
192  1111111111111111111111111111111111111111111111111111111111111111
256  0000000000000000000000000000000000000000000000000000000000000000
320  1111111111111111111111111111111111111111111111111111111111111111
384  1111111111111111111111111111111111111111111111111111111111111111
448  1111111111111111111111111111111111111111111111111111111111111111
```

<details><summary>3. assembler</summary>

``` asm
	s_movk_i32 s6, 0xc0
	v_and_b32_e32 v3, s6, v0
	v_add_u32_e32 v1, 63, v0
	v_cmp_eq_u32_e32 vcc, 64, v3
	v_mov_b32_e32 v2, 0x7f
	s_load_dwordx2 s[0:1], s[4:5], 0x0
	s_load_dword s2, s[4:5], 0x18
	s_load_dword s4, s[4:5], 0x20
	v_cndmask_b32_e64 v4, 0, 1, vcc
	v_cmp_lt_u32_e32 vcc, v1, v2
	v_addc_co_u32_e32 v1, vcc, 0, v4, vcc
	v_mov_b32_e32 v2, 0x80
	v_cmp_eq_u32_e32 vcc, v3, v2
	v_cndmask_b32_e64 v2, 0, 1, vcc
	v_cmp_eq_u32_e32 vcc, s6, v3
	v_addc_co_u32_e32 v2, vcc, v1, v2, vcc
	v_lshlrev_b32_e32 v0, 2, v0
	s_waitcnt lgkmcnt(0)
	s_ashr_i32 s5, s4, 31
	v_mov_b32_e32 v1, s1
	v_add_co_u32_e32 v0, vcc, s0, v0
	s_lshl_b64 s[0:1], s[4:5], 2
	v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
	s_ashr_i32 s3, s2, 31
	v_mov_b32_e32 v3, s1
	v_add_co_u32_e32 v0, vcc, s0, v0
	v_addc_co_u32_e32 v1, vcc, v1, v3, vcc
	s_lshl_b64 s[0:1], s[2:3], 2
	v_mov_b32_e32 v3, s1
	v_add_co_u32_e32 v0, vcc, s0, v0
	v_addc_co_u32_e32 v1, vcc, v1, v3, vcc
	global_store_dword v[0:1], v2, off
	s_endpgm
```

</details>

**Comment by misos1** [comment]
Here is another case:
``` c++
hc::array_view<int> a(1);
a[0] = 0;
parallel_for_each(hc::tiled_extent<1>(512, 512), [=](hc::tiled_index<1> i) [[hc]]
{
	if(i.local[0] == 256)a[0] = 10;
});
printf("%i\n", a[0]);
```
This prints 0. dump-gfx900.isa:
``` asm
...
; %bb.0:                                ; %"_ZZ4mainENK3$_0clEN2hc11tiled_indexILi1EEE.exit"
	s_endpgm
.Lfunc_end0:
...
```
Comparing local id with values less than 256 is working but not with 256 and greater values.

**Comment by david-salinas** [comment]
Adding the HCC attribute "[[hc_flat_workgroup_size(512)]]" to the parallel_for_each allows the kernel to use workgroup sizes greater than 256.  I've tried this with the above examples, and I see the expected behaviour.

**Comment by misos1** [comment]
So hc_flat_workgroup_size(X) when is X above 256 tells compiler that it should expect local size up to X, seems it is different from opencl reqd_work_group_size which disallows different local sizes than specified but on hcc seems I can use also local size 256 on kernel with hc_flat_workgroup_size(512).

Then I think default should be [[hc_flat_workgroup_size(1024)]] for all kernels (so no optimizations which assumes local size less than or equal to 256 like is on opencl) unless I provide some attribute like lets say [[hc_i_will_not_pass_dynamic_workgroup_size_greater_than(256)]] to enable such aggressive optimizations as are done now for all kernels without hc_flat_workgroup_size.

I hope current situation is only temporary. At least this should be mentioned somewhere because it can be hard to find what is wrong https://github.com/RadeonOpenCompute/hcc/issues/705 (this is the only place which can google find where is mentioned hc_flat_workgroup_size). Maybe it should generate runtime error when I run kernel which does not support local size greater than 256 with greater local size.

Is there plan enable local size up to 1024 by default and use rather some attribute like opencl reqd_work_group_size to enable these aggressive optimizations?

**Comment by david-salinas** [comment]
@misos1 thanks for your feedback.  We're looking at how we can improve the setting of the workgroup size; what the default should be, as well as documenting it, and giving users better control over it.  Possibly a compiler option to change the default size - which could be overridden by the attribute on the parallel_for_each.
