### ISSUE TITLE
Question: Multi GPU parallel_for_each

### ISSUE THREAD

**Issue by PhilipDeegan** [RadeonOpenCompute/hcc#907]
I'm trying to benchmark something, and I'm not sure where the bottleneck is. I'm getting

``` ### HCC STATUS_CHECK Error: HSA_STATUS_ERROR_INVALID_ALLOCATION (0x1003) at file:mcwamp_hsa.cpp line:2562 ```

It happens sooner on an 8GB Vega 64 than a 16GB FE so I imagine it's VRAM

Does HCC automatically use all GPUs available? Is there a simple multi GPU example around?

Thanks

**Comment by scchan** [comment]
Could you try this example on your system?  It gathers a list of accelerators on a system and launches PFEs on everyone of them. 
https://github.com/RadeonOpenCompute/hcc/blob/clang_tot_upgrade/tests/Unit/HC/multi_acc_array.cpp

**Comment by PhilipDeegan** [comment]
will do!

**Comment by PhilipDeegan** [comment]
I've gotten something together based on this now, but I'm having trouble getting an increasing index per device to differentiate which device is being used for the lambda

is there a way to access "get_seqnum" from the device within a lambda?

I'm hoping "get_seqnum" is the 0+ ID for the actual device

**Comment by PhilipDeegan** [comment]
hmm, I'm having some hanging issues

no hangs with gdb, perhaps a race condition?

https://github.com/Dekken/statick/blob/master/hcc/main.cpp#L141 this in particular

if I call "dev_lambda" sequentially it's fine, but as threads it causes the first one to hang forever

**Comment by PhilipDeegan** [comment]
is it infeasible to use a KalmarDevice within a thread? hangs/segfaults 

```
Thread 4 "hcc" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff23f5700 (LWP 17215)]
__GI___pthread_mutex_lock (mutex=0x6c2d74003131786d) at ../nptl/pthread_mutex_lock.c:65
65	../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x6c2d74003131786d) at ../nptl/pthread_mutex_lock.c:65
#1  0x0000000000416781 in __gthread_mutex_lock (__mutex=0x6c2d74003131786d) at /usr/lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/x86_64-linux-gnu/c++/6.5.0/bits/gthr-default.h:748
#2  std::mutex::lock (this=0x6c2d74003131786d) at /usr/lib/gcc/x86_64-linux-gnu/6.5.0/../../../../include/c++/6.5.0/bits/std_mutex.h:103
#3  Kalmar::KalmarDevice::get_default_queue (this=0x6c2d74003131782d) at /opt/rocm/bin/../hcc/include/kalmar_runtime.h:402
#4  0x000000000041aac4 in hc::accelerator::get_default_view (this=<optimized out>) at /opt/rocm/bin/../include/hcc/hc.hpp:841
#5  sparse(int, char**)::$_0::operator()(unsigned long) const (this=0x7fffffffdce0, dev_id=2) at main.cpp:111

```

**Comment by PhilipDeegan** [comment]
nevermind I was doing something daft! I got it working thanks
