### ISSUE TITLE
`__float128` is not supported on this target

### ISSUE THREAD

**Issue by psteinb** [RadeonOpenCompute/hcc#944]
Hi, I copying this bug report as it might be targetted to this repo a bit better perhaps.

### What is the expected behavior
-  hcc/clang compiles a very simple example submitted in [#146](https://github.com/ROCmSoftwarePlatform/rocFFT/pull/146)

### What actually happens
-  the following error is thrown
```
[ 50%] Building CXX object CMakeFiles/complex_forward_1d.dir/complex_forward_1d.cpp.o
/opt/rocm/hcc/bin/hcc   -I/opt/rocm/rocfft/include -isystem /opt/rocm/include -isystem /opt/rocm/hip/include -isystem /opt/rocm/hsa/include -isystem /opt/rocm/hcc/include  -Wno-unused-command-line-argument -hc -fPIC -std=gnu++11 -o CMakeFiles/complex_forward_1d.dir/complex_forward_1d.cpp.o -c /home/steinbac/software/rocfft/repo/docs/samples/complex_forward_1d.cpp
In file included from /home/steinbac/software/rocfft/repo/docs/samples/complex_forward_1d.cpp:2:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/vector:60:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stl_algobase.h:64:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stl_pair.h:59:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/move.h:57:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/type_traits:269:39: error: __float128 is not supported on this target
    struct __is_floating_point_helper<__float128>
                                      ^
1 error generated.
make[2]: *** [CMakeFiles/complex_forward_1d.dir/complex_forward_1d.cpp.o] Error 1
make[2]: *** Deleting file `CMakeFiles/complex_forward_1d.dir/complex_forward_1d.cpp.o'
make[2]: Leaving directory `/data/steinbac/software/rocfft/repo/docs/samples/build'
make[1]: *** [CMakeFiles/complex_forward_1d.dir/all] Error 2
make[1]: Leaving directory `/data/steinbac/software/rocfft/repo/docs/samples/build'
make: *** [all] Error 2
```

### How to reproduce
- using centos 7.4.1708
- using `rocm-dev` 1.9.307-1
- clone+checkout #146
- cd docs/samples 
- `mkdir build`
- `cd build`
-  `CXX=`which hcc` cmake ..`

### Environment
| Hardware | description |
|-----|-----|
| GPU | gfx803 |
| CPU | Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz |

| Software | version |
|-----|-----|
| rocm-dev | 1.9.307-1 |
| rocm-dkms | 1.9.307-1 |
| HCC | 1.2.18451-1 |
| hsakmt | 1.0.0-7.el7 |

**Comment by AlexVlx** [comment]
@psteinb (hello again!), you would probably benefit from compiling in standard C++ and not extended GNU C++ in this case. Changing the original CMakeLists.txt to include `set(CXX_EXTENSIONS OFF)` should do the trick, I expect.

**Comment by psteinb** [comment]
@AlexVlx thanks for the pointer - I played around a bit on the command line and found that with rocm 1.9.307 replacing `-std=gnu++14` with `-std=c++14`. I see that `set(CXX_EXTENSIONS OFF)` reverts that back again to `c++14`. thanks a bunch!
